### ISSUE TITLE
please add freebsd support package in release

### ISSUE THREAD

**Issue by blusewang** [nats-io/nats-server#1080]
see title

**Comment by kozlovic** [comment]
Ironically, we would not be able to cross-compile (we use CGO_ENABLED=off) because of this commit that added freebsd support :-) https://github.com/nats-io/nats-server/commit/a1bda5cad507e8ae09d1a4757848bb0585ff8d7a

Adding freebsd in our cross-compile script would produce error:
```
Stderr: go build github.com/nats-io/nats-server/server/pse: build constraints exclude all Go files in /Users/ivan/dev/go/src/github.com/nats-io/nats-server/server/pse
```
which leads to: https://github.com/golang/go/issues/24068.

That being said, I believe that NATS Server is part of the FreeBSD. There is a maintainer in our Slack that use to say that he updated it at each new release. Will try to reach out on Slack.

**Comment by cougarwww** [comment]
please add freebsd support package in release

**Comment by kozlovic** [comment]
@cougarwww We can't for the reason stated in previous comments. We build using CGO_ENABLED=off and the server/pse for freebsd uses C, so we would have to change that first.

**Comment by philpennock** [comment]
For clarity: the above PR which fixes this issue does so by doing exactly what @kozlovic said, because he is of course right.

The above PR adds support for cross-compiling _only_ for FreeBSD/amd64.  There are struct offsets which need to be pre-calculated on any architecture where we want to be able to avoid cgo, and I only have access to an amd64 box for this.

If you care about other hardware architectures, please take a look at the PR (which I'm cautiously optimistic will land) and create a per-architecture file in `server/pse/pse_freebsd_${GOARCH}.go` which does the same things.  We can figure out as those arise if we want to just copy `pse_freebsd_amd64.go` or if it makes more sense to abstract out the per-architecture constants and endianness variable to reduce code duplication.

**Comment by philpennock** [comment]
The next release of binaries for `nats-server` should include a FreeBSD/amd64 binary.
