### ISSUE TITLE
Does nats itself contain a load balancing policy？

### ISSUE THREAD

**Issue by DoMySon** [nats-io/nats-server#1116]
I suggest that you can configure a load balancing policy similar to that of nginx

**Comment by derekcollison** [comment]
For most clients if you provide multiple servers, or if DNS returns multiple A records the clients will randomly select the server to connect to.

We have long looked at how we may be able to dynamically balance out a cluster, but is not as straightforward as one might think.

**Comment by DoMySon** [comment]
But in most cases, nats does not know the performance of the host machine, how can it ensure that the better the performance of the machine is assigned to more messages?

**Comment by derekcollison** [comment]
Hence the reason we have not introduced anything beyond random selection. It is non-trivial to understand what "load" means and what is used to determine how to balance.

Most of the time however a single NATS server can flood a network connection, but not always so that is one to look at. Another might be memory which is aligned usually with number of connections. Rarely do we run out of CPU, but on underpowered machines this can happen of course.

**Comment by DoMySon** [comment]
Every actual operating environment is difficult to identify.I mean, can users control the load balancing policy?

**Comment by derekcollison** [comment]
They are difficult for sure, but again it can be simplify via resource constraints, network bandwidth, CPU and memory.
