### ISSUE TITLE
Cannot say when subscription is registered across entire cluster

### ISSUE THREAD

**Issue by kapralius** [nats-io/nats-server#1142]
- [X ] Feature Request or Change Proposal
 
After client subscribes for a subject, NATS does not provide any kind of signal indicating the client that subscription propagation to entire cluster has completed. What I mean is absence of a signal with meaning "since this moment, if any other client publishes a message matching this subject, the message will be delivered to you". 

I'm finding lack of this signal as problematic for case of "request snapshot + subscribe for updates" pattern: 

1. client --> nats-server-A: SUB "data.>"
2. client --> server: send snapshot request 
3. server --> client: send snapshot response
4. server --> nats-server-B: publish message "data.xyz"

If I understand the protocol correctly, there is no guarantee that in the moment when the "server" is publishing the message "data.xyz", the subscription (RS+) from "nats-server-A" has been propagated to "nats-server-B" and incorporated into its interest list (whatever tiny this time window is). In such case the first update(s) generated by the server might not been delivered to the client (which would cause detection of gap and immediate requesting for patch etc.) 

In my specific use case the snapshot RPC goes outside of NATS over a direct TCP connection between client and server, but IMHO the issue might occur even if the entire communication including RPC goes via NATS.

Is my understanding of this phenomenon correct? If so, is it possible to avoid it in the current NATS or some future enhancement?

Thanks, Ondrej

**Comment by kozlovic** [comment]
@kapralius The first thing to remember is that NATS is at-most-once, so even if there was a guaranteed propagation of subscription interest on server B before your server app sends messages on "data.xyz", the snapshot response message could very well get lost but not the updates (connection disconnects, reconnect buffer size not big enough to hold message, etc.., connection then reconnects) and not the updates.

The fact that your snapshot req/response is outside of NATS does add to the possibility of subscription propagation interest "race" though. For instance, I assume that your "server" application sends the snapshot response then the updates "data.xyz", but your client application processes the snapshot response and NATS messages differently, so right there, you may need to ensure that processing of updates is not done prior to processing of the snapshot response.

So assuming that your client app makes sure to process the snapshot response before any NATS messages on `data.xyz`, there are several cases:

- if client and server share the same NATS Server: no issue (again expect for possibility of lost NATS message)

- if client and server connect to different NATS servers in the same cluster: since the snapshot request is not sent on NATS, there is indeed a risk that your server app receives the snapshot request, the sends the snapshot response (not through NATS) and then sends through NATS the first updates (data.xyz) before the subscription interest on "data.>" is sent from NATS A to NATS B. As you said, the window is tiny and given that your client app would have to send an RPC to your server app, this may be enough time for the subscription interest to reach server B.

- if client and server connect to different NATS servers in different clusters (gateway): it actually comes down to the situation described above when the gateway is in optimistic mode since the NATS server B would send the data.xyz message regardless of interest to a server in the first cluster. As long as that server has already the subscription interest, things will be fine. If that server did not, then yes, you will possibly miss the update.

If you have some freedom in the subject space (data.xyz), you could have a setup phase. For instance, suppose your client subscribes to `data.>` but the actual updates would be sent to `data.updates.xyz`, then you could have `data.setup` reserved and your server application could send NATS requests there prior to send the actual updates. If your server does not get an update, it is assumed that the subscription interest is not yet registered. The client application would have to reply to the `data.setup` request obviously to let the server app know that it is ready.

But again, even with all above in place, especially when clustering or super-clustering is involved, there may be cases where routes or gateway connections will be dropped, and you may miss some updates. It is up to you to decide if the setup phase is worth it or not.

**Comment by kapralius** [comment]
@kozlovic, thank you for your quick answer!

If I'm not getting you wrong, your "setup-phase" suggestion holds mainly for one-to-one scenario, where the server publishes updates specifically for certain client, therefore it can first send NATS-req on "data.setup" and wait for the response as an update trigger. 

However, what I had on my mind are applications where the server publishes a stream of incremental data (like game world changes or incremental market data from exchange) to potentialy big number of clients. At the client start, the client requests the server for current snapshot(s) but otherwise the server is stateless w.r.t. clients - it does not track client subscriptions nor publish a special feed per client. Server just pushes stream of data updates to the middleware - some of the substreams might be subscribed by multiple clients, some might be subscribed by none. 

When initially writing about absence of some signal or acknowledging that the client subscription has been propagated over entire system, I basically wondered why the commands SUB and RS+ are fire-and-forget instead of being callbacked (req-resp) - having messages SUB-ACK and RS+ACK. Semantics of RS+ACK would be "I've incorporated the subscription to my internal interest list" and for SUB-ACK it would be "I've incorporated the subscription to my internal interest list and all counterparties where I've sent RS+ have acknowdged with RS+ACK". This is maybe simple to design for single-cluster case, but probably complicated (but still managable) to be generalised to super-clusters.

Having concept of subscription acknowledgement, the client app could (optionally) wait for the SUB-ACK before doing further processing (P2P out of NATS in our case). If the acknowledge is not received within a timeout, it would be up to the client to retry the same SUB again...

I guess you have evaluated the use of req-resp subscription API when designing the NATS and rejected this way it as it increases the code complexity (by implementing reference counting and handling many corner situations) while does not provide full guarantees on subscription propagation anyway... So I agree the at-most-once written simple and pure but with bigger "hole" is better than a one with smaller but still non-zero "hole" having incredibly complex code.

**Comment by kozlovic** [comment]
> However, what I had on my mind are applications where the server publishes a stream of incremental data (like game world changes or incremental market data from exchange) to potentialy big number of clients. At the client start, the client requests the server for current snapshot(s) but otherwise the server is stateless w.r.t. clients - it does not track client subscriptions nor publish a special feed per client. Server just pushes stream of data updates to the middleware - some of the substreams might be subscribed by multiple clients, some might be subscribed by none.

I think I understand. But since you are not using NATS to send/recv snapshot req/response, how do you ensure that the response is sent/received/processed prior to updates? A client that starts creates the subscription to the stream it wants, then sends a non NATS RPC to get the snapshot. When your server receives that request, it must "stop the world" to make sure it is not sending updates that are "newer" than the snapshot it is generating. Again, the problem is that even when the server sends the snapshot response and then allows the updates to be sent again, there is no guarantee that the response will be received before the updates. Your client may be blocking the processing of updates before processing of the snapshot response I guess.

So that leaves the subscription propagation race that you have originally brought up. How often have you experience that race? Since you still need to expect dropped messages, etc.. your application needs to be able to handle that.

> I basically wondered why the commands SUB and RS+ are fire-and-forget instead of being callbacked (req-resp) - having messages SUB-ACK and RS+ACK. Semantics of RS+ACK would be "I've incorporated the subscription to my internal interest list" and for SUB-ACK it would be "I've incorporated the subscription to my internal interest list and all counterparties where I've sent RS+ have acknowdged with RS+ACK"

Because NATS is at-most-once, fire and forget system. It would not make too much sense to have this level of guaranteed for a subscription when at-most-once guarantee is offered. As a side note, NATS Streaming that offers at-least-once makes the subscription a request reply and does wait that the subscription is registered in the streaming cluster. The subscription is not automatically retried, though.

**Comment by derekcollison** [comment]
FYI initial value / delta update systems are a fairly well understood problem from the 90s. If the initial value and updates flow over NATS this would be fairly straightforward to implement, even with a complex merge function. 

Assuming a consistent backend that has a generational or version id. Say an integer that increments for each change to the backend.

NATS client subscribes to updates. Deltas can be supported with merge function. Until initial value received hold onto updates and version for update.

NATS client sends request for initial value. When received, processes updates that have been received so far. Drops those that are less than initial value version. Applies all others and unblocks update callback to simply apply update versus saving.

If you care about missing last update, have source heartbeat with last version known. If client detects a gap, reset and do the sequence above again.

**Comment by kapralius** [comment]
@derekcollison thanks for your comment. In the system where we considering to use NATS instead of existing reliable multicast solution we do use exactly the algorithm referenced by you - incremental versioning, snapshot with version, client first subscribes before requesting a snapshot RPC, buffering updates (deltas), after snapshot is received, the smaller deltas are discarded and expeced deltas are applied/merged-in to the snapshot.

And this is where we get to my issue. The algorithm, requires that the request for snapshot is sent only when it is guaranteed that from that moment on, if any matching update is published it will be eventually delivered to the subscriber. If this is not guaranteed, the subscriber might detect a gap with the first update received.


> A client that starts creates the subscription to the stream it wants, then sends a non NATS RPC to get the snapshot. When your server receives that request, it must "stop the world" to make sure it is not sending updates that are "newer" than the snapshot it is generating. Again, the problem is that even when the server sends the snapshot response and then allows the updates to be sent again, there is no guarantee that the response will be received before the updates. 

Using the described "versioned deltas and snapshot" algorithm, this is not an issue.

> So that leaves the subscription propagation race that you have originally brought up. How often have you experience that race? Since you still need to expect dropped messages, etc.. your application needs to be able to handle that.

This point is very correct. The thing is that in our system we are okay to bear with data misses and the subsequent recovery when it is justified by post-failure recovery caused by objective network/slow consumer/failover issues etc. We are, however, aiming not to design a system where data can be missed under non-failure circumstaces, just being a matter of randomness in timing. 


The current solution that we made up and we are currenly considering is this:
- each NATS broker in the cluster shall have a ProofProvider application connected to it as a client
- ProofProvider is subscribed to subject "subscription-proof"
- the only task of ProofProvider is to receive messages Check(subject, resp-subject) and upon receival it responds by Check-Ack(subject, my-nats-server-id) published on "resp-subject"
- the subscription procedure of any regular NATS client in the system (ie. non-ProofProvider) shall be following:
	1 subscribe the subject: SUB(subject)
	2 publish message Check(subject, resp-subject) on subject "subscription-proof"
	3 wait for receival of Check-Ack(subject) on "resp-subject" from each ProofProvider known in the cluster
	4 return

So by Check + CheckACK we are actually simulating acknowledged SUB, RS+ operations not provided by NATS. We are also aiming to find the best way how to generalise this algorithm to supercluster scenario.

**Comment by kozlovic** [comment]
@kapralius Should we close this or do you have more questions?

**Comment by kapralius** [comment]
Thanks for your answers, closing.

**Comment by derekcollison** [comment]
Just to restate, we do have the ability in NATS 2.1 to have an account import a system feature that allows an application to query the system for the number of subscriptions matching a given subject.
