### ISSUE TITLE
Messages to queue subscriptions are not distributed evenly

### ISSUE THREAD

**Issue by harrisa1** [nats-io/nats-server#1144]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:
As a consumer that is part of a queue subscription, it should receive a (roughly) equal proportion of the messages sent to that subject.
 
#### Proposed Change:
Currently the code handles queue subscriptions by randomly picking a place in the list of queue subscriptions and starting there.  This is fine if the nats instance is the first nats instance to receive this message (i.e. from a client).  [See https://github.com/nats-io/nats-server/blob/d44b0dec51f6f2b332d02959dda83c544f69fba3/server/client.go#L2814] However, if the nats instance receives the message from another nats instance it will "prefer" a local client over sending to another nats instance.  This is what causes the current problem.  Take this example with two nats instances in a cluster and 12 subscribers that are part of the same queue group:
Assume two subscribers connect to nats instance A and then 6 subscribers connect to nats instance B then 4 more subscribers connect to nats instance A, since the list of subscribers is kept in a slice which is automatically ordered you get this list structure on both nats instances:
0 - A
1 - A
2 - B
3 - B
4 - B
5 - B
6 - B
7 - B
8 - A
9 - A
10 - A
11 - A
If nats instance B receives a message for the queue it will pick at random from the list, if it picks 0-1 or 8-11 then it will route the message to nats instance A. Now nats instance A will redo the work done by nats instance B and pick at random from the list, however it will require use of 0-1 or 8-11 but because it will randomly pick it can pick 2-7, if it does then it will start iterating the list, this will always lead to nats instance A picking subscriber 8 if it randomly starts with 2-8, effectively sending 1x traffic to subscribers 0-1, 9-11 and 7x traffic sent to subscriber 8.

One possible solution for this is to have nats instance A honor the pick that nats instance B made (if possible) because nats instance B correctly uniformly distributed that message.

Another possible solution is to have all nats instances shuffle the list of queue subscribers before every message (or on a regular short interval or on a small number of messages).

#### Who Benefits From The Change(s)?
Anyone using a load balancer for connections and using queue subscriptions.
 
#### Alternative Approaches
One alternative approach is to not use a load balancer for connections and manage balancing connections in some other way, also all clients that wish to use the same queue subscription would need to use the same method for balancing connections and this could get very tricky with many subscribers and many different queue subscriptions.

Another alternative approach is to have more members of the queue subscription.  This will only lessen the severity because effectively "x" from the above example is smaller, it doesn't really fix the distribution problem.  It just means that when one instance gets 7x the messages compared to its peers that 7x will be smaller.

**Comment by kozlovic** [comment]
When a server receives a remote interest on a queue subscription (for the same group), it maintains locally a single subscription for the route. However, when comes the time to match the interest, the low level sublist code is "expanding" that single subscription into as many subscriptions that the queue weight is (the number of queue subs). So that will create a "block" of remote queue subscriptions. The bigger this block is and therefore the chances that the random number falls into this block, the likely the chance that the local sub that is after that block is going to receive the message.

So the fact that a server "favor" a local subscription when getting a message from the route is by design and desired behavior, however, depending on the size of block of remotes queue subscription, a local subscription will definitively get more messages.
We could look at how to improve this - but there would be performance impact since the match result that we get from the sublist is cached (and shared) so we can't shuffle it in a go routine without possibly breaking other go routines walking this set. We would need to work on a copy..

That being said, and although I think we should improve this, there is no stated guaranteed that the distribution will be uniform, we state that it is random. But I agree that the expectation so far since we were using math.rand is that the distribution would be uniform.

**Comment by derekcollison** [comment]
This is fixed via #1215
