### ISSUE TITLE
Ability to upgrade to 2.x without downtime

### ISSUE THREAD

**Issue by azhurbilo** [nats-io/nats-server#1187]
- Feature Request or Change Proposal
 
#### Use Case:
 
We want migrate from 1.x to 2.1.0 nats-server (we use Nats as RPC between all services in our org)
Is it possible to do it without downtime?

There is documentation https://docs.nats.io/nats-server/nats_admin/upgrading_cluster but in 2.x I see https://github.com/nats-io/nats-server/releases/tag/v2.0.0 Backward incompatibility "routing protocol" don't allow connect new 2.x nodes to existing 1.x cluster nodes 😞

May be you know some workaround?

**Comment by kozlovic** [comment]
> May be you know some workaround?

Not really, since the route protocol has changed, 2.x servers won't be able to connect to 1.x servers. 
That being said, you need to think of what you mean by "without downtime". Even if you were to upgrade to servers of the same major version, when a server is recycled, its client connections will be closed. There is always a risk of losing data when that happens. (although we did add lame duck mode in latest 1.4).
