### ISSUE TITLE
Log size limit?

### ISSUE THREAD

**Issue by xzzh999** [nats-io/nats-server#1197]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)
 
#### Versions of `nats-server` and affected client libraries used:
nats-server 2.1.0

#### OS/Container environment:
windows server 2012 R2

#### Steps or code to reproduce the issue:
long time run
 
#### Expected result:
log auto truncate
 
#### Actual result:
the log is keep increasing to 88GB and eat all disk space...

**Comment by kozlovic** [comment]
@xzzh999 The NATS Server has never had an auto-rotate capability. What we have is the ability to send a signal to re-open the logfile, which on Unix allows the user to move the file first and the signal to re-open (which will recreate the logfile). Unfortunately on Windows, that may not work because you can't move a file that is opened by a process, and you would have to run as a service to be able to send the reopen "signal". That being said, when running as a service you would likely use the syslog instead.
I have started to look at adding basic auto-rotate file log feature, which could be helpful for some users (Windows users namely).

**Comment by kozlovic** [comment]
@xzzh999 I have added a `log_size_limit: <size>` option. Could you try and see if that works for you? The PR has been merged into master.

**Comment by xzzh999** [comment]
@kozlovic
Sorry for the late reply, that's very kind, thanks.

**Comment by xzzh999** [comment]
@kozlovic 
now it's log like this:
```
nats-server.log
nats-server.log.2019.12.13.14.37.57.558600300
nats-server.log.2019.12.13.14.40.28.743600300
nats-server.log.2019.12.13.14.40.54.504600300
nats-server.log.2019.12.13.14.41.08.049600300
```
can u offer a max rotate file count option?

**Comment by kozlovic** [comment]
@xzzh999 I think that offering auto-rotation is already an improvement compared to previous version (especially for Windows where one cannot move the file and issue the "reopen" signal since the file is owned by the server and can't be moved). However, adding this other option would mean that the server would have to get all the logs on startup (order them) to be able to apply the limit. Even at runtime, it would have to remember the names of the previous files in order to delete the old ones. It is possible, of course, but maybe that should be left to the admin to move/remove the old logs if desired?

**Comment by xzzh999** [comment]
@kozlovic emmmm.........., that make sense

**Comment by philipfoulkes** [comment]
What is the unit of `log_size_limit`?

**Comment by kozlovic** [comment]
@philipfoulkes The unit is bytes, but can be expressed using `MB`, `GB`, etc.. Check the documentation:
https://docs.nats.io/whats_new#log-rotation
https://docs.nats.io/nats-server/configuration/logging#using-the-configuration-file

**Comment by philipfoulkes** [comment]
Thank-you @kozlovic
