### ISSUE TITLE
Is it possible to publish messages directly on the server side?

### ISSUE THREAD

**Issue by JulianZhao** [nats-io/nats-server#1205]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

I want to publish messages on the server side,  messages just like SYS Topics in MQTT,
without creating a NATS client.

#### Proposed Change:
 Add some methods like:
```
server.Publish(subj string, data []byte)
server.PublishMsg(m *Msg)
```

**Comment by derekcollison** [comment]
While this is fairly easy to add, the issue that I worry about is bypassing the authentication process and binding to an account when multiple accounts are utilized.

Since the server is in Go utilizing the Go client is straightforward, and the loopback on 127.0.0.1 is highly optimized. This also does not bypass any of the authorization or authentication.

**Comment by JulianZhao** [comment]
@derekcollison, thank you for your quick answer!
Yes, the Go client is an option.
I found the internal system client and server.sendInternalMsgLocked in the code, can I use it to publish messages securely?

**Comment by derekcollison** [comment]
They are non-public and are used for internal messages for the system account.

**Comment by JulianZhao** [comment]
Thank you.
