### ISSUE TITLE
Enhancement:  Match server identities with certificate RDNs regardless of order

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#1600]
## Enhancement

Look at extending matching a certificate DN to an identity regardless of the certificate's individual RDN order.  Some users have services that can change the order of RDNs when regenerating their certificates, which then creates a mismatch between the certificate DN and vs what was originally configured in the server.

**Comment by LionelCons** [comment]
While you're at it, it would be good to add support for multiple `CN`.

My CA issues certificates looking like `CN=John Doe, CN=123456, CN=jdoe, OU=Users, OU=Organic Units, DC=acme, DC=com`. With ActiveMQ, I can just put this exact string to get certificate based authentication.

With NATS, only the first `CN` is taken. I have to use a string like `CN=John Doe,OU=Organic Units+OU=Users,DC=com,DC=acme` to authenticate.

FWIW, `openssl x509` supports a `compat` format as well as a `RFC2253` format:
```
    Display the certificate subject name:
        openssl x509 -in cert.pem -noout -subject
    Display the certificate subject name in RFC2253 form:
        openssl x509 -in cert.pem -noout -subject -nameopt RFC2253
```

Maybe NATS should support RFC2253?

**Comment by derekcollison** [comment]
Thanks, that is a good suggestion. Will have @wallyqs take a deeper look and respond back.

**Comment by wallyqs** [comment]
Hi @LionelCons, thanks again for the feedback. Since release 2.1.8 it would be able to support RFC2253 in the certs if you define the auth user as in the output from `openssl x509 -in cert.pem -noout -subject -nameopt RFC2253` , for example given a cert generated like this: 

```sh
export CLIENT_ID=example
openssl req -newkey rsa:2048  \
            -nodes -keyout client-$CLIENT_ID.key \
            -subj "/CN=John Doe/CN=123456/CN=jdoe/OU=Users/OU=Organic Units/DC=acme/DC=com" \
            -addext extendedKeyUsage=clientAuth -out client-$CLIENT_ID.csr

openssl x509 -req -extfile <(printf "subjectAltName=DNS:localhost,DNS:example.com,DNS:www.example.com") \
             -days 1825 -in client-$CLIENT_ID.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out client-$CLIENT_ID.pem
```

The result with openssl when using the RFC2253 nameopt would be: 

```sh
openssl x509 -in cert.pem -noout -subject -nameopt RFC2253
subject=DC=com,DC=acme,OU=Organic Units,OU=Users,CN=jdoe,CN=123456,CN=John Doe
```

and that exact RFC2253 string could be used for auth and should work:

```hcl
	authorization {
	  users = [
	     { user = "DC=com,DC=acme,OU=Organic Units,OU=Users,CN=jdoe,CN=123456,CN=John Doe" }
           ]
	}
```

Before the 2.1.8 release the auth string would have had to be something like, we have kept this behavior for backwards compatibility as well so the match is still attempted by the server:

```hcl
	authorization {
	  users = [
	     { user = "CN=jdoe,OU=Users+OU=Organic Units" }
           ]
	}
```

this is due to the implementation of how Go displays RDNs and that won't change now...  so would recommend trying with the RFC2253 order as you mention to be more exact in the match.
