### ISSUE TITLE
Allow account verification without resolver, using only jwt

### ISSUE THREAD

**Issue by zub0r** [nats-io/nats-server#1744]
#### Current status
Currently, when a NATS server is verifying an user with jwt, the server needs to either fetch trusted accounts from remote resolver or simply load it from memory resolver. That prevents deploying NATS with truely decentralized authentication/authorization.

#### Proposed Change:
Would it be possible to allow users to embed account jwt which signed them inside user jwt? That way the server wouldn't need to use resolver at all, because it could verify if `accountPubKey` was signed in `accountJwt` by the operator.
```
{
  "type": "user",
  "name": "trustedUser",
  "iss": "accountPubKey",
  "issJwt": "accountJwt",  <===
  "sub": "userPubKey",
  "nats": {}
}
```

#### Use Case:
Decentralized authentication & authorization.

#### Who Benefits From The Change(s)?
- people who need dynamic accounts but don't want to maintain/integrate account server for that matter
- people who want to issue jwts in their apps, e.g. after using different auth strategy

#### Alternative Approaches
No idea. I was under impression that NATS already works this way, but stumbled upon this during implementation.

**Comment by matthiashanel** [comment]
Hi @zub0r thanks for your the request. 

I have considered something like this before. 
So, I'm going to first call out some of the issues with the suggested approach and then want to point you at an alternative that we support right now (in trunk at least). 
I hope that the alternative would suite your needs as well, am willing to help with setup and would welcome any feedback you might have. 

**Problems** with the approach are that you give up the ability to retroactively alter the account. 
You'd have to update every deployed user JWT in order to do that.
Among other things, you give up the ability to disable accounts by setting them to be expired.
This could be mitigated slightly by adding a revocation list to the operator, but  to distribute that you'd have to reconfigure the server and restart it. (we could improve on that by allowing a reload there, but you'd have to touch the config of every server still)
I see another issue with different account versions. If you proved the account as part of your connect, wouldn't you expect that you get the exact settings that where specified, not the most recent ones we found through another client to the same account connecting with a more recent version of the account?
Similarly, in a cluster or super cluster. What if one client connects with one version of the account to one server and the other client with the other version to another?

The **alternative** is to use our nats based account resolver that has recently been added. 
At it's core the functionalities of the account server was moved into the nats-server (no need to run/monitor a separate process). 
The functionalities where then improved (clustering was made easier, support for removal was added) and exposed via nats (you can easily publicize new accounts yourself by sending a request with an account jwt). 

Below description will work if you build nats-server (optionally nsc) with the most recent sources.

What you need is a system account and the new resolver configuration. 
nsc was modified to generate a default system account on `nsc init` as well as `nsc add operator --sys`
set the account server url to your cluster address using `nsc edit operator --account-jwt-server-url "nats://localhost:4222"`
Then you can easily generate the nats config you'd need usign `nsc generate config --nats-resolver` 

What this generates can also be configured manually by including this in the configuration of every `nats-server`:
```
# Operator named DEMO
operator: ...
# System Account named SYS
system_account: ABTFVAXATJEOKIBESJ3LO3JTAAMDCZ755DLAAGGSDMH5TU6HSFL7YNYY

# configuration of the nats based resolver
resolver {
    type: full
    # Directory in which the account jwt will be stored
    dir: './jwt'
    # In order to support jwt deletion, set to true
    # If the resolver type is full delete will rename the jwt.
    # This is to allow manual restoration in case of inadvertent deletion.
    # To restore a jwt, remove the added suffix .delete and restart or send a reload signal.
    # To free up storage you must manually delete files with the suffix .delete.
    allow_delete: false
    # Interval at which a nats-server with a nats based account resolver will compare
    # it's state with one random nats based account resolver in the cluster and if needed,
    # exchange jwt and converge on the same set of jwt.
    interval: "2m"
}
```

Once you have your cluster running like this you can add accounts using `nsc` and push them with `nsc push ...`
If you set the account server url to your clusters address, you can avoid the -u option.

What `nsc` does under the covers, if it has the private key for a system account user, is the following: 
connect to the cluster using credentials for a system account user.
Send a request containing your new/updated account JWT to  `$SYS.REQ.CLAIMS.UPDATE`
Every server receiving this will respond with a status message.
If enough respond with ok you are done. 
If some do not, the jwt will eventually be propagated to them. 

Is this something you could work with and solve your problem?
If so I'm eager to get your feedback.

**Comment by zub0r** [comment]
Hi @matthiashanel, thank you for your answer!

I understand the issues you described and the proposed solution that utilizes nsc to propagate account updates to servers.
I like the idea with update request and I had something similar in mind.

The thing is, I don't find it very practical to integrate nsc into an app, especially if someone's codebase is outside of go world.
I'm okay with using nsc to generate the operator and maybe to create some static config for local testing, but I would preferably configure accounts remotely in an app with jwt, without the need to touch the server config (or its tooling) again.

I'm not familiar with the internals of NATS but here are some naive ideas how I imagined it running in decentralized stateless mode and addressing your points:

- **accounts updating & revocation** - Servers could keep the latest verified version of accounts in memory, when any client connects with newer account version, the update event you mentioned would be propagated to all servers automatically and affected listening clients would be notified - they would need to renegotiate their jwt with the auth server, or be disconnected after some delay. (I suppose the disconnection is already happening regardless of used auth strategy when needed.)
- **updating all user jwts** is a non-issue, because there should be a mechanism for renewing them on client due to expiration, reconnection, or at least for initial auth, anyway. I know that the docs say that NATS doesn't use jwts as session, but it could, right?
- **disabling accounts** - could be some symbol or flag in the memory structure of latest verified accounts. I see the statefulness problem here due to restart, could be solved by rolling restart or providing statefull option to store disabled accounts locally before syncing it after restart automatically.
- **account versions & clusters** - a client would be rejected when trying to connect with an account that is not up to date with latest version on server, forcing it to fetch new valid jwt from auth server or stay disconnected
- **minimal configuration** - nats server could start with an operator (and optionally cluster) config only, accounts and users would be created dynamically and decentralized,
- this might allow nats to run in stateless mode with huge flexibility from the application perspective
- full cluster restart would cause gradual update of latest accounts as clients reconnect, rolling restart would even keep latest accounts up

If the usage of nsc is ultimately inevitable, do you plan to create some nsc wrappers for various languages?

Thank you again for providing an alternative solution and sorry for all that nonsense. 
I think I'll either use something from what you suggested or stick to single account and separation on user level with jwt for simplicity.

Regarding jwts signed with typescript - there seems to be a signature verification [issue](https://github.com/nats-io/ts-nkeys/issues/24) loading it on server.

**Comment by matthiashanel** [comment]
Hi @zub0r nsc is not needed for what you want. The only difference is that, instead of embedding a generated account jwt in a user jwt you'd publish it to `$SYS.REQ.CLAIMS.UPDATE`

All you need is the [jwt](https://github.com/nats-io/jwt)(or any json) and [nkey](https://github.com/nats-io/nkeys) libraries to generate the necessary jwt artifacts. Once you generated the account jwt, you just have to send it as a request to the subject mentioned (using system account credentials). 

The jwt library basically provides accessors for the json stored inside the jwt + utility functions. 
When you dynamically generate accounts you will probably only specify a few values, just look up what json that'd produce and use any json library instead.

The nkey library is used for key generation and signing. It exists for multiple languages as well. (every language with a nats library that supports our jwt scheme)
With it, you can sign the json you generated, append the signature and have a jwt. 

When you do it this way you can even use nsc in addition. 
Download and inspect accounts or (provided you possess the correct keys) make modifications after the fact.

A lot of your suggestions are essentially what the nats resolver does today. 
Disk is used (simple mount, no shares) to help with complete cluster restarts, but if you don't need that, just have it use a memdrive. 
To cover small outages or individual servers coming up empty, account jwts are synchronized in an eventually consistent way.

We will soon be releasing v2 of our jwt library. it clears up some namespace issues and fixes the signing issue.

I'm not saying that embedding the account does not make sense. It is however a lot more than just reading a field. 
And we have something that seems to fits the bill pretty well already. Would you agree?

**Comment by zub0r** [comment]
Sorry for delay.
So if the only thing necessary to create an account is to sign it with system account and send to `$SYS.REQ.CLAIMS.UPDATE` - that will fit my needs perfectly!
Thank you for thorough explanations - it helped a lot.

**Comment by matthiashanel** [comment]
@zub0r you need:
* The setup as outlined above so that the nats based resolver is used.
*  you need to sign the account with an operator key (or better operator signing key). 
* Then send the resulting artifact to `$SYS.REQ.CLAIMS.UPDATE` using a connection that was created using system account credentials as the system account is where the receiver for this subject is running in.
