### ISSUE TITLE
No response from any moment in leaf node configuration

### ISSUE THREAD

**Issue by wuddl6** [nats-io/nats-server#1751]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [v ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

2.2.0-beta.33
master branch (2e28de50)

#### OS/Container environment:

windows 2010

#### Steps or code to reproduce the issue:

The configuration is the same as https://github.com/nats-io/nats-server/issues/1743
While testing the fixed, I found another issue.

I used nats-rply and a simple request client written by go.

simple client code is as follows.
```
func main() {
    var urls = flag.String("s", nats.DefaultURL, "The nats server URLs (separated by comma)")
    var userCreds = flag.String("creds", "", "User Credentials File")
    var showHelp = flag.Bool("h", false, "Show help message")

    log.SetFlags(0)
    flag.Usage = usage
    flag.Parse()

    if *showHelp {
        showUsageAndExit(0)
    }

    args := flag.Args()
    if len(args) < 2 {
        showUsageAndExit(1)
    }
    subj, payload, numStr := args[0], []byte(args[1]), args[2]
    num, err := strconv.Atoi(numStr)

    // Connect Options.
    opts := []nats.Option{nats.Name("NATS Sample Requestor")}

    // Use UserCredentials
    if *userCreds != "" {
        opts = append(opts, nats.UserCredentials(*userCreds))
    }

    // Connect to NATS
    nc, err := nats.Connect(*urls, opts...)
    if err != nil {
        log.Fatal(err)
    }
    defer nc.Close()
    
    var reqCount, resCount int = 0, 0
    
    // Subscribe reply subject
    reSubject := "RE"
    subRe, err := nc.QueueSubscribe(reSubject, reSubject, func(m *nats.Msg) {
        resCount++
        log.Printf("Received [%v,%d] : '%s'", m.Subject, resCount, string(m.Data))
    })
    subRe.SetPendingLimits(-1, -1)
    
    for i :=0; i < num; i++ {
        err := nc.PublishRequest(subj, "RE", payload)
        if err != nil {
            if nc.LastError() != nil {
                log.Fatalf("%v for request", nc.LastError())
            }
            log.Fatalf("%v for request", err)
        }

        reqCount++
        log.Printf("Published [%s,%d] : '%s'", subj, reqCount, payload)
    }

    for (resCount < reqCount) {}
}
```
This simple client subscribe 'RE' to receive response.
And publish_request num times.

**Step of execution**
1) nats-rply subscribe 'foo' on srv-2
2) execute request-client foo hello 10 on leaf-2
3) execute request-client repeatedly

#### Expected result:

The request-client receives all responses.

#### Actual result:

The request-client doesn't receive responses from any moment.
![err2](https://user-images.githubusercontent.com/74340852/100398864-c944ff00-3093-11eb-9e11-70dff90ef729.png)

Looking at the srv-2 log, count of publish response to 'RE' is 20, but count of RMSG is 17.
And 'processRemoteUnsub parse error' logged at srv-2.
```
[22940] 2020/11/27 08:15:42.506173 [TRC] [::1]:6222 - rid:2 - <<- [RS- ncs $G RE RE]
[22940] 2020/11/27 08:15:42.506173 [ERR] [::1]:6222 - rid:2 - processRemoteUnsub parse error: 'ncs $G RE RE'
[22940] 2020/11/27 08:15:42.506173 [INF] [::1]:6222 - rid:2 - Router connection closed: Protocol Violation
[22940] 2020/11/27 08:15:42.506173 [DBG] Attempting reconnect for solicited route "nats://localhost:6222"
```
It is not reproduced in the release version.
Full logs are attatched.
[1127_natslog.zip](https://github.com/nats-io/nats-server/files/5605450/1127_natslog.zip)

**Comment by kozlovic** [comment]
@derekcollison The issue is that the server does not correctly processes an LS- with origin cluster sent through a route. The parser does not distinguish if coming from ROUTER it should treat as LS- or RS- so if it is a queue unsub, the parsing completely fails (returns error), if it is not a queue unsub, then there would be a DBG trace saying that it does not find the account (as the cluster name is interpreted as the account name).

The question to you is this: what is the intent of sending LS- with cluster origin to the route? Here we see that if an origin exists, the LS+/LS- is sent as opposed to RS+/RS-:
https://github.com/nats-io/nats-server/blob/a4f1b6ccc8795b9ec32546932cffbe39128e38dd/server/route.go#L1234-L1236

If you can tell me what the server should be doing with the origin cluster in the LS- protocol coming from a route, we can add code in the parser to properly parse an LS- coming from route, but again, I don't know what the server needs to do with the origin cluster information in the processing of an UNSUB.
If there is no need, then the simple change:
```
if isSubProto && len(sub.origin) > 0 && c.route.lnoc {
```
would be enough to turn the unsub to RS- only (although trace-wise we would have an LS+ vs RS-, which is weird) and solve the disconnect issue.

**Comment by derekcollison** [comment]
For UNSUB nothing, just remove interest. Origin cluster is to detect sophisticated loops with leafnode configs.

**Comment by kozlovic** [comment]
> For UNSUB nothing, just remove interest. Origin cluster is to detect sophisticated loops with leafnode configs.

So question for you @derekcollison. What do you would want the behavior be. I will propose 3 approaches and I can easily do any of those:

- Do not send the LS- with origin, but a simple RS-. No code change in parsing/tracing. But the tracing would look a bit "odd":
```
LS+ abc $G foo bar
RS- $G foo bar
```
- Send an LS- but without the origin. The receiving side would just check if it is 'R' or 'L' and trace accordingly, but parsing code of route UNSUB remain same.
```
LS+ abc $G foo bar
LS- $G foo bar
```
- Send an LS- with origin (as of today). The receiving side would trace accordingly and parsing of route UNSUB need to be altered to support origin (even if just ignore for now).
```
LS+ abc $G foo bar
LS- abc $G foo bar
```

**Comment by derekcollison** [comment]
I think `LS-` without origin.
