### ISSUE TITLE
WebSockets as a first class citizen

### ISSUE THREAD

**Issue by matti** [nats-io/nats-server#1783]
Apparently now nats-server supports websockets - this is a bit unclear because no documentation outside of #1309 exists for it.

Also for it to be meaningful feature, it would need client support like #315

**Comment by matti** [comment]
Also the latest v2.1.9 says `nats-server: nats.conf:1:0: unknown field "websocket"`

And I don't understand why #1309 says that tls is *required* for websockets if tls is already handled in kubernetes ingress (or in cloudlfare)

**Comment by ripienaar** [comment]
This feature is not released yet, scheduled for 2.2.0

**Comment by matti** [comment]
I think it's bad communication to close issues etc related to this before it is actually out. I hope this issue, or some other will be kept open until it's really out so that people can follow.

**Comment by ripienaar** [comment]
The issues are to track the development of the features. Not the release. So across most open source projects it’s common practise to close issues when the feature is complete - and towards the next release update docs, release notes and such.

**Comment by matti** [comment]
fair enough, so if this issue is closed, where can I follow this specific feature to be released? just keep polling nats releases daily?

**Comment by ripienaar** [comment]
GitHub “watch” feature can notify you when a new release ships

The release notes will cover what’s new etc

**Comment by kozlovic** [comment]
@matti Sorry about the confusion. In GitHub, when an issue/enhancement request is reported and a PR is submitted to address the issue/enhancement, when the PR is merged, GitHub automatically closes the corresponding issue.

In some case, like this one, the feature is available in the main branch, but not yet in a public release. This can be confusing indeed.

As for the tls required requirement, this is because we expect lot of users to use JWT bearer tokens and so want to make sure that the link is protected so those cannot be intercepted. But know that we have added a `no_tls` boolean that will bypass this requirement. Documentation is not available yet, as you have discovered.
We are doing our best, but we have a lot of things going on and would ask for a bit of patience from our community. Thanks!

PS: I will leave this issue opened until the public release is available.. advance warning: the release may be available before the documentation...

**Comment by askdesigners** [comment]
Any idea when this release might be ready?

**Comment by derekcollison** [comment]
2.2 release is starting RC phase now that JS clustering is in the main branch. Hoping for early Feb.

**Comment by talhof8** [comment]
What does it mean in terms of STAN support? Any official plans to support it as well?

**Comment by kozlovic** [comment]
@talhof8 Once NATS Server 2.2.0 is out, you can always connect NATS Streaming to a separate NATS Server. Otherwise, would have to wait a new release that embeds NATS 2.2.0 in streaming server. However, Websocket is currently available only to Node.js clients (with nats.ws), so there would be no direct support of Streaming server or most of the other client libraries to talk websocket.

**Comment by kozlovic** [comment]
NATS Server 2.2.0 is now out with Websocket support. Some documentation: https://docs.nats.io/nats-server/configuration/websocket.
