### ISSUE TITLE
MQTT Clients compatibility issue with '.' char and use in Eclipse Tahu MQTT specification

### ISSUE THREAD

**Issue by petedavis** [nats-io/nats-server#1879]
There is an issue using NATS.io as a MQTT broker for with the Eclipse Tahu specification.

Unfortunately the root namespace used for the topic contains a '.' char. (See [page 12 of the specification](https://www.eclipse.org/tahu/spec/Sparkplug%20Topic%20Namespace%20and%20State%20ManagementV2.2-with%20appendix%20B%20format%20-%20Eclipse.pdf))

Given that the '/' topic delimiter chars are converted to NATS topic alternative, should the NATS topic delimiter chars be converted or escaped for MQTT clients? 

Could there be a known substitution used internally, like converting '.' to '_' and NATS clients would need to know about?

So MQTT client publish to `spBv1.0/group/message/node` and NATS client subscribe to `spBv1_0.group.message.node`?

**Comment by kozlovic** [comment]
As you have probably observed, currently NATS would reject an MQTT topic that contains '.' because it is used as token delimiter in NATS.

If we do any conversion, then it would be ok to document so that NATS users that want to exchange between NATS and MQTT would have to alter their NATS subjects, however, the problem is that internally NATS converts incoming MQTT messages to NATS format, and convert back when sending to MQTT subscribers.

That is, a MQTT publisher that sends on `foo.bar/baz` would be converted on ingest to `foo_bar.baz`, matched against any subscription and then sent to MQTT subscribers as `foo.bar/baz` (reverse conversion). 

Seem ok, right? The issue is if the MQTT topic contains the converted character. In the example above, suppose that MQTT publishes on `foo.bar/baz/bar_bat`, then it would be converted to `foo_bar.baz.bar_bat` but on the way to the MQTT subscribers it would have to be converted and now would be `foo.bar/baz/bar.bat` which does not match.

**Comment by sandrokeil** [comment]
See also https://github.com/nats-io/nats-server/issues/3482
