### ISSUE TITLE
what should happen when leaf node L connect to two isolated clusters(e.g. A and B)

### ISSUE THREAD

**Issue by hl3w22bupt** [nats-io/nats-server#2001]
I have set up two NATS cluster _A_ and _B_, they both don't know each other.  After that, I start up a _leaf node_ _L_.

When I publish some message through _cluster A_, _leaf node_  _L_ can work as expected, subscriber to _leaf node L_ could receive all messages . **But the subscriber in _cluster B_ could also receive the messages. However, what surprised me more is that queue subscriber in _cluster B_ could not receive any messages**. I was certain that there are no any other queue subscribers in the same queue group.

**What should be the proper behavior in this case?**  subscriber and queue subscriber in _cluster B_ seems contradict each other

**Comment by derekcollison** [comment]
We would need to see your config setup and how you were subscribing etc.

**Comment by hl3w22bupt** [comment]
> We would need to see your config setup and how you were subscribing etc.

Thanks for you reply : )
Here my config and test case is.

_nats node in cluster A_:
```
server_name: nats-3
host: 0.0.0.0
port: 4423
prof_port: 6003
http_port: 8233
cluster {
  host: localhost
  port: 5253
  routes: [
    "nats-route://localhost:5251",
  ]
}
leafnodes {
    port: 7423
}
```

_nats node in cluster B_(Indeed, it is not a cluster but a nats node):
```
server_name: nats
host: 0.0.0.0
port: 14222
prof_port: 16202
http_port: 18222

leafnodes {
    port: 17422
}
```

_leaf node L_:
```
server_name: nats-leafnode
host: 0.0.0.0
port: 4272
prof_port: 6272
http_port: 8272

leafnodes {
    remotes = [
        {
          url: "nats://locahost:7423",
        },
        {
          url: "nats://locahost:17422",
        },
    ]
}
```

publish message to nats node in cluster A:
> nats-pub -s nats://localhost:4423 foo gogooggo

subscribe message from leaf node L:
> nats-sub -s nats://localhost:4272 "foo"

subscribe message from cluster B:
> nats-sub -s nats://localhost:14222 "foo"
> nats-qsub -s nats://localhost:14222 "foo" xyzzz

In my test, in cluster B side, nats-sub could receive message from cluster A, but nats-qsub could not.

**Comment by derekcollison** [comment]
Thanks, would it be possible to try with the latest release of 2.2.0 and let us know if the problem persists there? I believe it was fixed.

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats-server/releases

**Comment by hl3w22bupt** [comment]
> Thanks, would it be possible to try with the latest release of 2.2.0 and let us know if the problem persists there? I believe it was fixed.

seems still can not work. problem still there.

![image](https://user-images.githubusercontent.com/3297112/111304136-57b7ad80-8690-11eb-864e-74dfe560e19f.png)
![image](https://user-images.githubusercontent.com/3297112/111304224-728a2200-8690-11eb-91cb-be2eb29e5e60.png)
![image](https://user-images.githubusercontent.com/3297112/111304986-5fc41d00-8691-11eb-894c-d1042ded9b8c.png)

**Comment by derekcollison** [comment]
ok will have @matthiashanel take a look.

**Comment by matthiashanel** [comment]
@hl3w22bupt , when you tested this, was the subscriber that connects to the leaf node running? (workaround at the end)

I can somewhat reproduce the issue, even without queue subscriber.
Basically if I have a subscriber to `foo` on the leaf node, my subscription to `foo` on cluster `B` will receive messages sent to `A`.
If I shut down the subscriber in the leaf node, my subscription to `foo` on cluster B does NOT receive messages sent to `A`.

I assume you had a subscriber in the leaf node running, which is why regular publishes seemed to work.
Subscriptions and queue subscriptions are treated slightly differently, which is why you do not see the message. 
This is a similar case to not having a subscription in the leaf node.

![issue-2001](https://user-images.githubusercontent.com/19881388/111388820-571a1980-8686-11eb-971a-c86e0d4e47dc.gif)

The reason for this is that the directions in which leaf nodes connect matters for our routing.
In your case you have `A <- L -> B`
In particular this matters for routing of messages that do not originate in a particular server, as would be the case for L.

What you can do to avoid this is:
- You could just directly connect A/B via leaf node connections. 
- Or change the leaf node connection to include a new option `hub: true` in one of your remotes in the leaf node.

```
server_name: nats-leafnode
host: 0.0.0.0
port: 4272
prof_port: 6272
http_port: 8272

leafnodes {
    remotes = [
        {
          url: "nats://localhost:7423",
        },
        {
          url: "nats://localhost:17422", hub: true
        },
    ]
}
```

Let me know if either of these two work for you - Matthias

**Comment by hl3w22bupt** [comment]
> had a subscriber in the leaf node running

Ok, got it, and indeed I had a subscriber in the leaf node running. 
Also, I have tried to set `hub:true` in leafnode config, and it works for me. Thanks so much

**Comment by matthiashanel** [comment]
@hl3w22bupt glad it worked! Just be careful when your cluster B changes from single node to cluster of nodes. There, the missing message problem will extend to nodes in B not connected to by the leaf node. There I'd advise opening a port in L and have every server in B connect to L and remove the remote for B in L.
