### ISSUE TITLE
$JS.API.CONSUMER.MSG.NEXT does not adhere to Nats request/reply semantics

### ISSUE THREAD

**Issue by cjbottaro** [nats-io/nats-server#2044]
## Defect

```
PUB $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.843ba4e2 11\r\n{\"batch\":1}\r\n
MSG test 1 $JS.ACK.test.test.18.1.33.1616869628558889000.0 13\r\n
Hello, world!\r\n

PUB $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.38ceb950 11\r\n{\"batch\":1}\r\n
MSG test 1 $JS.ACK.test.test.16.2.34.1616869663547879100.0 15\r\n
Does this work?\r\n

PUB $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.a0654805 51\r\n{\"batch\":1,\"expires\":\"2021-03-28T20:01:06.570714Z\"}\r\n
MSG request-8a04d799.a0654805 1  0\r\n
```

Notice the first two requests get replies on the "test" subject instead of the requested reply_to subject.

But then if you use the "expires" option with a datetime 5 seconds in the future when there are no message to be delivered, the server:
1. Doesn't wait 5 seconds; it responds immediately
2. _Does_ respond to the requested reply_to

## Extra info

```
$ docker run --rm nats:2.2-alpine -DV -js
[1] 2021/03/28 19:56:45.746479 [INF] Starting nats-server
[1] 2021/03/28 19:56:45.746525 [INF]   Version:  2.2.0
[1] 2021/03/28 19:56:45.746540 [INF]   Git:      [0e3c723]
[1] 2021/03/28 19:56:45.746554 [DBG]   Go build: go1.16.2
[1] 2021/03/28 19:56:45.746567 [INF]   Name:     NDE6QLW4MO7TKGV7J6Q5TBOKSAWGTNMWWCFKWR4JKEEII7JYDZGJRQLZ
[1] 2021/03/28 19:56:45.746581 [INF]   ID:       NDE6QLW4MO7TKGV7J6Q5TBOKSAWGTNMWWCFKWR4JKEEII7JYDZGJRQLZ
[1] 2021/03/28 19:56:45.746653 [INF]   Node:     bD8NB7Au
[1] 2021/03/28 19:56:45.746692 [DBG] Created system account: "$SYS"
[1] 2021/03/28 19:56:45.747359 [INF] Starting JetStream
[1] 2021/03/28 19:56:45.747911 [DBG] JetStream creating dynamic configuration - 2.88 GB memory, 30.08 GB disk
[1] 2021/03/28 19:56:45.749419 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
[1] 2021/03/28 19:56:45.749539 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[1] 2021/03/28 19:56:45.749560 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[1] 2021/03/28 19:56:45.749580 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[1] 2021/03/28 19:56:45.749596 [INF]
[1] 2021/03/28 19:56:45.750102 [INF]       https://github.com/nats-io/jetstream
[1] 2021/03/28 19:56:45.750122 [INF]
[1] 2021/03/28 19:56:45.750229 [INF] ---------------- JETSTREAM ----------------
[1] 2021/03/28 19:56:45.750275 [INF]   Max Memory:      2.88 GB
[1] 2021/03/28 19:56:45.750292 [INF]   Max Storage:     30.08 GB
[1] 2021/03/28 19:56:45.750313 [INF]   Store Directory: "/tmp/nats/jetstream"
[1] 2021/03/28 19:56:45.750357 [INF] -------------------------------------------
[1] 2021/03/28 19:56:45.750465 [DBG]   Exports:
[1] 2021/03/28 19:56:45.750481 [DBG]      $JS.API.>
[1] 2021/03/28 19:56:45.750637 [DBG] Enabled JetStream for account "$G"
[1] 2021/03/28 19:56:45.750678 [DBG]   Max Memory:      2.88 GB
[1] 2021/03/28 19:56:45.750693 [DBG]   Max Storage:     30.08 GB
[1] 2021/03/28 19:56:45.751699 [DBG] Recovering JetStream state for account "$G"
[1] 2021/03/28 19:56:45.752007 [DBG] JetStream state for account "$G" recovered
[1] 2021/03/28 19:56:45.752664 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2021/03/28 19:56:45.752945 [DBG] Get non local IPs for "0.0.0.0"
[1] 2021/03/28 19:56:45.753369 [DBG]   ip=172.17.0.3
[1] 2021/03/28 19:56:45.753540 [INF] Server is ready
```

```
# nats -s host.docker.internal stream info test
Information for Stream test created 2021-03-27T18:16:22Z

Configuration:

             Subjects: test
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0.00s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited

State:

             Messages: 2
                Bytes: 96 B
             FirstSeq: 1 @ 2021-03-27T18:27:08 UTC
              LastSeq: 2 @ 2021-03-27T18:27:43 UTC
     Active Consumers: 1

```

```
# nats -s host.docker.internal consumer info test test
Information for Consumer test > test created 2021-03-27T18:21:22Z

Configuration:

        Durable Name: test
           Pull Mode: true
         Deliver All: true
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant

State:

   Last Delivered Message: Consumer sequence: 36 Stream sequence: 2
     Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
         Outstanding Acks: 2
     Redelivered Messages: 2
     Unprocessed Messages: 0
```

## Expected result

The reply should be sent to the requested reply_to subject regardless of any combination of payload options `batch`, `expires`, and `no_wait`.

Also, with `expires` set in the future, the server should not respond immediately if there are no messages to be delivered.

**Comment by wallyqs** [comment]
The first two messages are indeed being rewritten due to how consuming messages from JetStream works so that is expected, for pull subscribers this means to fetch a batch of messages the most straightforward way is to make a classic NATS request (create inbox, subscribe, auto unsub on the expected number of messages, then publish the request and wait for results).
The third empty message that is being received, is likely due to the expires time being a date though it was changed into a duration in nanoseconds, so what the subscriber is receiving is what could be called a *status error message* through the [headers](https://github.com/nats-io/nats-server/blob/master/doc/adr/0004-nats-headers.md) which is also a feature from NATS Server v2.2.
The docs about expires were wrong as you found out so I have sent PR to fix: https://github.com/nats-io/nats.docs/pull/239/files

**Comment by cjbottaro** [comment]
> the most straightforward way is to make a classic NATS request (create inbox, subscribe, auto unsub on the expected number of messages, then publish the request and wait for results).

I think I’m misunderstanding something fundamental here; I thought that’s what I was doing. There is indeed a subscription to `request-8a04d799.*` and I thought the way to make a classic request was to set a reply_to to some uniq ID under that subscription.

Thanks for the help!

**Comment by wallyqs** [comment]
Hi @cjbottaro, what I mean is that for pull subscribers the 'old style' request is what seems to work best that would be in terms in the NATS protocol something like this for example, if we want to fetch only 1 message:

``` sh
sub request-8a04d799.unique SID # <-- where SID is a subscription identifier that is usually just a number that is increment
unsub SID 1 # <-- remove interest after 1 message

# Publish the request, here 0 bytes for pull subscribers, the empty payload means just fetch one and 'wait forever until one is delivered'
pub $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.unique 0 \r\n
```

Then the message will be delivered using the original subject as when it was published, so a simple NATS client can publish this:

```
PUB test 13\r\n
Hello, world!\r\n
```

So then pull subscriber would receive that message on the subscription SID, though the inbox subject or reply_to has been rewritten the subscription identifier has been not:

```
MSG test SID $JS.ACK.test.test.18.1.33.1616869628558889000.0 13\r\n
Hello, world!\r\n
```

Since `unsub SID 1`  was called then that subscription SID 1 will also be removed automatically.  In case of making a `batch: 5` request it would have looked like:

```
unsub SID 5
pub $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.unique 30 \r\n
{"batch": 5}
MSG test SID $JS.ACK... # 5 times
```

When making the fetch batch request, the result of making that request could be an error for a number of reasons but that would be an empty payload message with the status being included in the header. In case of making a `no_wait` request and no messages being ready then the result would be a status empty message with a 404 status description.  In the nats.go client what is implemented right now is that, the first request is a `no_wait` request to get an error right away in case of no messages, and then fall back into a making another request with only the batch size with a client side timeout that calls unsubscribe again in case it times out (to avoid messages being delivered into the subscription).

**Comment by nuharaf** [comment]
Hopefully this is not a wrong place to ask. Wouldnt subject rewriting mess-up the routing for intermediary server ? I assume the one doing rewriting is the origin jetstream server, so how the intermediary server able to route the message to the correct client ?

**Comment by cjbottaro** [comment]
Ohh, thank you, I had no idea there were two different style of requests.

**Comment by cjbottaro** [comment]
This still doesn't seem to work for me...
```
PUB $JS.API.CONSUMER.MSG.NEXT.test.test request-8c0a3c58.03738409 32\r\n{\"batch\":1,\"expires\":1000000000}\r\n
```
Which I think says "wait for up to 1s for a stream message to arrive, if none do, send a blank message". I do get a blank message, but it's after many seconds of waiting (not one like requested):
```
MSG request-8c0a3c58.03738409 1  0\r\n
```

Also, imo, it would be nice if Jetstream implemented some kind of "simple fetch" that used a "new style" Nats request/response and semantics similar to how Faktory works: https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#fetching-jobs (which uses Redis' BLPOP under the hood).

For example...
```
PUB $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.843ba4e2 11\r\n{\"simple\":true,\"expires\":2000000000}\r\n
```
... and you'd either get a stream message or a blank message after 2s, but either way, the response would be sent to `request-8a04d799.843ba4e2`.

It seems way more simple to me. In your example, what if someone uses the expires option?
```
unsub SID 5
pub $JS.API.CONSUMER.MSG.NEXT.test.test request-8a04d799.unique 30 \r\n
{"batch": 5, "expires": 2000000000}
MSG test SID $JS.ACK... # 1 time then expires hits
```
What happens in that case? I would guess a blank message gets sent to the subscription with subject `request-8a04d799.unique`, but it wouldn't automatically unsub because that's only two messages being sent there.

**Comment by ripienaar** [comment]
@cjbottaro  Isn't this simple pull just the same as batch:1 and expires:2s - if batch pull delivered the empty message at the right time?

@derekcollison seems to me waiting is only processed when messages come in rather than any form of timer for the actual requests, meaning 408's come at, apparent, random times rather than at the end of waiting period

**Comment by derekcollison** [comment]
We do not run a timer for each unfulfilled request correct. We could tighten up as well but this should be controlled at the client layer IMO in terms of application logic.

**Comment by cjbottaro** [comment]
> @cjbottaro Isn't this simple pull just the same as batch:1 and expires:2s - if batch pull delivered the empty message at the right time?

It's close, but not quite the same I think. Because of the subject rewriting, I don't think we can just use a simple "new style" request/response.

But anyway fwiw, it turned out that writing a Jetstream consumer using batch:1 but no expires option at all is extremely easy with the framework I'm using, so all good here! It does hinge on the idea that any pending (queued) requests on the server are immediately cancelled if `unsub <sid>` is called, which I'm assuming is the case.

Thanks!

**Comment by ripienaar** [comment]
subject rewriting is required, you need to know where messages were delivered to originally in many cases - I personally avoid needing to do that, but its a very common thing, I dont thnk we'd be serving our users by not doing it.

**Comment by derekcollison** [comment]
Going to close but please feel free to reopen if needed.
