### ISSUE TITLE
prevent stalled wait for client to gateway

### ISSUE THREAD

**Issue by shkim-will** [nats-io/nats-server#2082]
## Feature Request

recently, I experienced network issue between clusters affect main cluster. gateway slowed down > client to gateway flushing slowed and client stalledWait occur.
it blocked some clients inbound message, as a result whole system blocked.

#### Use Case:
one main cluster & other sub clusters connected with gateway
massive messages produces on main cluster and copied to sub clusters

#### Proposed Change:
flushing gateway (maybe network issue) don't block client inbound message
 1. when client kind is GATEWAY flushClients() call flushSignal(), not flushOutbound()
 2. Add gateway option, not stall channel when client kind is GATEWAY
may need an option for proposal

#### Who Benefits From The Change(s)?
gateway network issue don't affect to local cluster

#### Alternative Approaches
small write_deadline & max_pending reduce stalledWait but exist

**Comment by kozlovic** [comment]
This would not really solve the problem. When a client connection produces a message, the server will try to flush (meaning write to the TCP socket) from this producer's "readLoop" to the connections of matching subscriptions. If in the list there is a connection that has a socket buffer that is full, the tcp write may block up to the write deadline. This will delay any other connection that follows in the list. This is regardless of the presence of a stalled channel in the outgoing connections.

Not creating the stalled channel on the gateway connection would potentially cause an unbound memory growth since we would never slow down the publisher. This would not be good.

Note that only CLIENT connections are restricted in term of stalling and checking the pending outbound buffer size. Not long ago, all connection types would be subject to that, which meant that some fast producers could possibly cause a ROUTE or GW connection to be closed due to accumulation of outbound data. This was not "fair" because these connections transport data for all producers, and may be considered as part of the system, so they are excluded from that in recent versions.
However, I think we still need to stall a CLIENT that is a fast producers, to give a chance to those other type of connections to drain the data.
What we *could* maybe do, is in flushClients(), if the producer is a CLIENT and the "consumer" (the cp variable) is a CLIENT too, then only then try to flush in place. A CLIENT would still stall in deliverMsg() if the destination's connection is a GW that has a stalled channel, but at least there would be no risk of blocking the CLIENT's readLoop in flushOutbound() if the GW connection is "stuck".

**Comment by shkim-will** [comment]
I think flushing only in client - client situations is good.
