### ISSUE TITLE
`$JS.API.CONSUMER.MSG.NEXT.<STREAM>.<DUR>` doesn't reject streams or consumers that don't exist

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#2107]
For an existing stream, a client asks for messages to be pulled into a subscription.
The consumer doesn't exist, the request specifies 10 seconds waiting, at which time the client API bails, however the server didn't provide any information about the consumer not existing.

```text
<<<<<<< 2021-04-12T19:38:01.932Z
< SUB _INBOX.ACDJ7UJXSRTTU665YSHPEG 2␍␊
< UNSUB 2 1␍␊
< PUB $JS.API.CONSUMER.MSG.NEXT.ACDJ7UJXSRTTU665YSHP94.me _INBOX.ACDJ7UJXSRTTU665YSHPEG 48␍␊{"no_wait":true,"batch":1,"expires":10000000000}␍␊
> PING␍␊
< PONG␍␊
>>>>>> 2021-04-12T19:38:11.934Z
```

The main issue is a particular application design. In the scenario, the consumer and stream are created out of band, the consumer configuration is given to the client, which then proceeds at given intervals to check for messages. However, subsequently, the consumer is deleted.

The expected behavior would be for either no responders to be raised, or for the server to inform the client that the consumer doesn't exist.

**Comment by derekcollison** [comment]
Spoke with @ripienaar and decided to keep behavior as is for the time being to prevent an application from fast spinning when someone deletes a consumer out from underneath of them.

**Comment by jon-whit** [comment]
I can understand why you might not want to support this. But as a client I certainly don't like this behavior. It seems very counter intuitive from an application perspective. If I attempt to subscribe to a durable that doesn’t exist, I should be told as much. And if a consumer is actively subscribed to a durable when that durable is deleted, I would expect a client’s `.subscribe(..)` or equivalent method to raise an error indicating deletion of said durable.

With Cloud Pubsub for example you get a `NOT_FOUND` error if the underlying subscription gets deleted underneath a subscriber actively consuming off of it.

So this behavior is certainly odd behavior from a client experience point of view.

**Comment by derekcollison** [comment]
Clients like the Go client will fail if the consumer does not exist when creating the subscription. This is specific to when the consumer is deleted out from underneath of a pull based consumer.

We may want to add it but again are concerned over applications spinning and sending API requests as fast as they can.

**Comment by jon-whit** [comment]
The unfortunate side-effect of that choice is that clients won't be informed by the server that something is wrong with the consumer they are attempting to pull messages off of. Consequently they will continue to try and pull messages, and thus add more traffic to the server unecessarily.

If a client isn't informed by the server that something is wrong, how should the client programmatically react to the issue at hadn?

**Comment by derekcollison** [comment]
If you receive a timeout, you could check that the consumer is still there or that JS has not been turned off for your account etc.

**Comment by derekcollison** [comment]
Also, since each failed request has to time out, they may keep sending but they will have not checked for errors. Meaning that if we did return an error of `consumer not found` they would just do that much much faster.

**Comment by ripienaar** [comment]
> The unfortunate side-effect of that choice is that clients won't be informed by the server that something is wrong with the durable consumer they are attempting to pull messages from. Consequently they will continue to try and pull messages, and thus add more traffic to the server unnecessarily.
> 
> If a client isn't informed by the server that something is wrong, how should the client programmatically react to the issue at hand?

They will be informed by a timeout, this situation is not one that will happen jusst because a consumer is deleted, it will also happen when say a super cluster is split and the consumer is temporarily not accessible.

Pull consumers are ideal for cases where you have a large, unknown size, consumers such as when using auto scalers etc, exactly the kidns of consumers you dont want to end up running `for { pull(time.Minute) }` and have that then fail instantly.

**Comment by tpihl** [comment]
I think it’s important to signal the client, see my feature request #701 on the go client.

If I do a context based next, I may never find out that my subscription is dead and that I may need to recreate my consumer. And subscribesync is the advice I got for when I want to adjust max wait see #699. And since I want to remain idle unless there is work to so, I do a context based subscribesync where I only cancel the context as part of graceful application shutdown. 

Should we push the responsibility to the program using our clients to NOT trust the client waiting for the next msg (or an error/callback), force them to do a timeout/re-setup if they listen to a stream with silent periods of time?

**Comment by ripienaar** [comment]
If you do context based subscribes like that you have to enable heartbeats. 

Context based is there only for contexts with timeouts. Not for long running ones IMO as there isn’t really a way to make that reliable in a distributed system

**Comment by tpihl** [comment]
Where is heartbeats and flowcontrol described (how to use...)?

**Comment by ripienaar** [comment]
Hmm can’t find now. 

Heartbeats will send you a empty message with 100 status when the stream is idle 

flow control will send you a status 100 message with a reply subject. You have to reply to them to give the server hints about how fast you can go for push consumers.

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.
