### ISSUE TITLE
Per-Subject Retention

### ISSUE THREAD

**Issue by cliffburdick** [nats-io/nats-server#2285]
Hi, I have a use case where I have N subjects that I want the retention for each of those subjects to be the same, but not a global policy for all. The use case would be something like IoT where I have 30,000 different publishers, and I only want the last N messages from each publisher. Currently the stream would be the lowest granularity for retention, but that would only set a retention policy for all publishers in that stream. 

I would imagine the solution being something like you could still set stream retention, but subjects (including wildcards) could also have their own retention, that if set, would override the stream one.

**Comment by ripienaar** [comment]
This landed in the server @ https://github.com/nats-io/nats-server/pull/2284 with a setting that allows for max messages limits per subject.  Age is already by default per subject of course, missing is size per subject but I am ok for the moment without that while we see how this shakes out.

JSM, CLI, Terraform, Schemas etc https://github.com/nats-io/jsm.go/issues/253

**Comment by tpihl** [comment]
Well, it makes sense to have a common value for all subjects instead of new filters. And I guess I can make multiple streams when I need different max per subjects. 

My ideal would of course to be able to have max 1 for x.y.snapshot.entity and then a lot more for x.y.changed.entity (maybe even able to truncate a subject for all .changed. before the .snapshot).  I my projection of of x.y.*.entity takes long, I’d persist the aggregate as a snapshot and truncate the older msgs for this entity.

That would always give me a fast aggregation read if I cannot keep a read-view in memory. But how fun would it be if everything already was fixed.

**Comment by ripienaar** [comment]
We will add roll ups as a follow up feature. 

You can publish a message on a subject and purge all on that subject prior to the sequence of that message. 

We might combine these 2 operations i to one.

**Comment by tpihl** [comment]
Question now that I can see this happen. Will the purge be blocking or lazy (will it be expensive?)

**Comment by derekcollison** [comment]
Right now we do the removes in place unless we can optimize to a compact or full purge call. Will keep an eye on it, we know how to optimize if needed.
