### ISSUE TITLE
discard policy of new need to support max messages per subject.

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats-server#2314]
Given a stream like this:

```
nats$ nats s info WORK_POOL -j
{
  "config": {
    "name": "WORK_POOL",
    "subjects": [
      "js.in.work_pool.*"
    ],
    "retention": "limits",
    "max_consumers": -1,
    "max_msgs_per_subject": 10,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 20000000000,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "new",
    "num_replicas": 1,
    "duplicate_window": 5000000000
  },
  "created": "2021-06-24T20:48:12.010176455Z",
  "state": {
    "messages": 11,
    "bytes": 528,
    "first_seq": 82,
    "first_ts": "2021-06-24T21:07:18.303339661Z",
    "last_seq": 92,
    "last_ts": "2021-06-24T21:07:18.309908177Z",
    "consumer_count": 0
  },
  "cluster": {
    "name": "lon",
    "leader": "n2-lon"
  }
}
```

I expect to be able to put max 10 messages into each subject and then I should be getting rejections.  But no rejections happen. In fact this combination of `max_msgs_per_subject: 10` and `discard: new` appears to entirely break per subject limits:

```
$ nats req js.in.work_pool.2 x --count 200
$ nats s info WORK_POOL
...
State:

             Messages: 200
```

Related:

```
Jun 24 21:03:27 n2-lon nats-server[1337]: [1] [ERR] JetStream failed to store a msg on stream 'one > WORK_POOL' -  maximum messages exceeded
```

Should not be ERR, its kind of a normal situation.

**Comment by derekcollison** [comment]
So for discard new we should not error? Debug? Advisory?

**Comment by ripienaar** [comment]
Debug is fine

**Comment by derekcollison** [comment]
ok simple non clustered test works fine.. hmm..

**Comment by ripienaar** [comment]
This was a R1 on a cluster.

**Comment by tpihl** [comment]
I think you should get error if you have discard new, max 10 per subject and already 10 in subject. 

The max per subject seems a bit clunky with discard new, because what do you do. If you want to do a roll up, you would prefer to insert it, make sure it’s there and then purge before it. 

But also if you have discard old with max per subject it gets tricky. When you purge by age, you know it’s time to roll up every 2 weeks or something.  But when you get an unanticipated number on the same subject, you loose data.

ideally only the roll up subjects should want a max per subject and discard old

the delta subjects should be retention new. And maybe an advisory when msgs for a subject is above a certain level? So “something” can do a roll up 

I’m just trying to figure out a robust simple eventing pattern with rollouts (I call them snapshots) and then events only containing what changed

**Comment by ripienaar** [comment]
The use case here is not for rollups - the use case is to make a capped stack. So I agree with you @tpihl - but that was not the problem I tried to solve when identifying the bug.

As it turns out there isn't a obvious bug - but there are some weirdnesses if you edit a stream that we'll fix :)

**Comment by derekcollison** [comment]
This should be fixed.
