### ISSUE TITLE
MQTT $share topic violation

### ISSUE THREAD

**Issue by ichadhr** [nats-io/nats-server#2386]
I just playing around using NATS with MQTT enabled and found I can't subscribe over `$share` topic which is feature for load balancing subscriber MQTT:

event if permission already given in config file:

```
authorization {
   MQTT = {
      publish = ["client.>", "test.>"]
      subscribe = ["client.>", "$share.>", "$MQTT.sub.>"]
   }
   users = [
      {user: user, password: password, permissions: $MQTT, allowed_connection_types: ["MQTT"]}
   ]
}
```

Subscribe:
```$share/group/test/topic```

Publish:
```test/topic```

Error in log:
```[27486] 2021/07/30 21:15:57.969304 [ERR] 192.168.1.127:57681 - mid:12 - Subscription Violation - User "user", Subject "$share.group.test.topic>", SID $share.group.test.>```

**Comment by kozlovic** [comment]
@ichadhr Shared subscriptions are a MQTT v5 feature and NATS Server's MQTT feature supports only v3.1.1 at this time. That being said, with your config, I am able to start a subscription on `$share/group/test/topic/#` (since it looks like you are using the wildcard at the end of the test/topic topic. Of course, this will not be a shared subscription, but I am not getting an auth violation:
```
$ go run main.go -broker tcp://127.0.0.1:1883 -user user -password password -topic "\$share/group/test/topic/#" -clean -qos 1 -action sub -id sub -num 100
```
and server log (unfortunately, have to enable `-V` for trace, and with JETSTREAM, a bit verbose, but looking for the `mid:` trace:
```
[39556] 2021/07/30 11:56:03.221903 [TRC] 127.0.0.1:64732 - mid:12 - ->> [CONNACK sp=false rc=0]
[39556] 2021/07/30 11:56:03.222142 [TRC] 127.0.0.1:64732 - mid:12 - <<- [SUBSCRIBE [$share/group/test/topic/# ($share.group.test.topic.>) QoS=1] pi=1]
```

Anyway, since you are trying to use shared subscriptions that are not supported, solving the auth issue would be moot if you really need shared subscriptions. I am closing this for now, but if you still have issues with regular subs, we can re-open or open a new one.
