### ISSUE TITLE
JetStream API deny permissions along leaf node connections are inserted to easily. 

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats-server#2388]
A leafnode will always insert deny clauses in `leafnode.go` function `processLeafnodeInfo`.
This is irrespective of the domain name used.

```txt
[42059] [INF] Adding deny export of "$JS.API.>" for leafnode configuration on "JSY" that bridges system account
[42059] [INF] Adding deny import of "$JS.API.>" for leafnode configuration on "JSY" that bridges system account
```

Specifically this should only be added when the domain names on either end of the leaf node connection are not empty and do not differ. Thus line `1012` should add a condition for `!s.sameDomain(info.Domain)` to only execute the code below then.

In the specific use case, jetstream is not even enabled on the leaf node.
Thus, we could just check for `opts.JetStream` instead. Meaning don't add the denies when JS is not enabled.

But consider such a daisy chained setup:
s1 (JetStream) <-ln- s2 (no JetStream) <-ln- s3 (JetStream)

Both approaches will break down.

The check for `!s.sameDomain` suffers from the domain not being settable without jetstream.

I'd suggest we make domain settable without jetsttream and only insert the denies when `!s.sameDomain(info.Domain)`

**Comment by derekcollison** [comment]
Thanks for the writeup. Will take a look. I know its nuanced since a given LN may not have JetStream enabled but they could still be in a separate domain. In that instance you can have a JetStream block with **enabled: false** but provide the domain name.

Still not comfortable with the domain name outside of JetStream. Longer discussion.

I will take Matthias test case and work on a solution.
