### ISSUE TITLE
Jetstream: Require Heartbeat when Flow Control is Set or provide alternative

### ISSUE THREAD

**Issue by scottf** [nats-io/nats-server#2520]
## Feature Request

1A. Require `idle_heartbeat` when `flow_control` is requested when creating a consumer; server returns an error when the consumer is not created correctly.
-or - 
1B. Default `idle_heartbeat` when `flow_control` is requested but `idle_heartbeat` is not supplied when creating a consumer.
-or-
2. Provide an api call to manually request a heartbeat status message

#### Use Case:

Currently if a consumer is created with flow control is set, but heartbeat is not, if a flow control message is missed, there is no way to recover without restarting the server. The consumer simply stops getting messages.

#### Proposed Change:

Implement option (1A or 1B) and/or 2

#### Who Benefits From The Change(s)?

Consumers can recover from missed flow control.

**Comment by kozlovic** [comment]
@derekcollison I think that this is a reasonable request since indeed, if the FC message is lost, then server will stop delivering. Server may send the HB with a "Nats-Consumer-Stalled" header, but only if consumer is configured with heartbeats :-)

So now the question is: does the server fail JS consumers (at least new ones, so we don't break existing deploys) if FC is set but not HB, or do we set a default if not set.

Libraries should have been updated to handle HBs even if the user is not configuring it (based on note for ADR-15: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-15.md#heartbeats):
```
Also, the library should always check for JetStream heartbeat (and flow control) status messages, regardless of how the subscription was created. That is, the checks should not be conditional to the IdleHeartbeat option passed to a subscribe API call.
```
So I believe it would be safe for the server to set a default if not provided, but honestly, wonder if server should not reject it to make sure user is aware that HBs need to be set.

**Comment by derekcollison** [comment]
Will let you, and @ColinSullivan1 and @scottf make the call.

**Comment by kozlovic** [comment]
After discussion, I vote for server to reject a configuration for FC without HB.

**Comment by derekcollison** [comment]
ok figure out who will do the changes to the server. Thanks.

**Comment by kozlovic** [comment]
So since I am looking into this, we can do either reject or set a default. I checked and the Go library would not complain if one calls js.Subscribe() with flow control but without explicit HB even if the server has set a default HB.
Again, I can do either, but I think @ripienaar had an argument in favor of rejecting. R.I., would you mind commenting here as to why it would be better to reject? Thanks!

**Comment by ripienaar** [comment]
It helps declarative or desired state based configuration management - k8s, github actions etc - if what you put in is what you get out since they will do a full compare over every property.  So unexpected changes could cause them to think the desired state does not match actual leading to issues.  Especially since consumers cant be edited.

Strong preference for rejecting invalid configs rather than fiddling it under the covers.

**Comment by kozlovic** [comment]
@scottf The change is in the PR #2533 and will now reject consumer creations with FC and no HB. But be aware that this may break apps or tests in client libraries. For instance, I will have to update the C client tests since there was a test where consumer was created with FC and no HB... So may want to let others know about this upcoming change.
