### ISSUE TITLE
JS: `num_redelivered` shows zero

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#2572]
I have the following test which does:

- creates a queue consumer with ack policy set to all.
- 100 messages are published
- the subscribers will only ack message 100
- the subscribers will nak any sequence that is not evenly divided by 3

```javascript
Deno.test("jetstream - ack policy in queue", async () => {
  const { ns, nc } = await setup(jetstreamServerConf({}, true));
  if (await notCompatible(ns, nc, "2.3.5")) {
    return;
  }
  const { stream, subj } = await initStream(nc);
  const js = nc.jetstream();

  const opts = consumerOpts();
  opts.ackAll();
  opts.queue("q");
  opts.durable("n");
  opts.deliverTo(createInbox());
  opts.callback((_err, m) => {
    if (m) {
      if(m.info.redelivered) {
        console.log(`R: ${m.seq}`);
      }
      if(m.seq === 100) {
        m.ack();
      }
      if(m.seq % 3 === 0) {
        m.nak();
      }
    }
  });

  const sub = await js.subscribe(subj, opts);
  const sub2 = await js.subscribe(subj, opts);

  for (let i = 0; i < 100; i++) {
    await js.publish(subj, Empty);
  }
  await nc.flush();
  await sub.drain();
  await sub2.drain();

  assert(sub.getProcessed() > 0);
  assert(sub2.getProcessed() > 0);
  assert(sub.getProcessed() + sub2.getProcessed() > 100);

  console.log(`sub1: ${sub.getProcessed()}   sub2: ${sub2.getProcessed()}` );

  const jsm = await nc.jetstreamManager();
  const ci = await jsm.consumers.info(stream, "n");
  console.log(ci);

  await cleanup(ns, nc);
});
```

The unexpected part is that on processing the stream, the info will report:
```
  num_redelivered: 0,
```

But in reality, it did resend:
```
R: 3
R: 6
R: 9
R: 12
R: 15
R: 18
R: 21
R: 24
R: 27
R: 30
R: 33
R: 36
R: 39
R: 42
R: 45
R: 48
R: 51
R: 54
R: 57
R: 60
R: 63
R: 66
R: 69
R: 72
R: 75
R: 78
R: 81
R: 84
R: 87
R: 90
R: 93
R: 96
R: 99

```

**Comment by ripienaar** [comment]
I made a go test in https://github.com/nats-io/nats-server/pull/2575 and it does show the problem

Looking at the code, I think we need to agree first on what NumRedelivered mean, for me it means the number of redeliveries a consumer did. If the same message had 10 redeliveries thats 10 NumRedlivered and this number must never reset for any acks or anything.

The code though has:

https://github.com/nats-io/nats-server/blob/c91f0fec3fc64fcfc3c7702dfc07b72a00cec9d5/server/consumer.go#L1519

Which suggests rather than a total count, this is how many message had redeliveries - a message with 10 redeliveries will count as 1

Further on a normal ack we remove the entry from the list - meaning a past redelivered message thats now acked will decrease this number

https://github.com/nats-io/nats-server/blob/c91f0fec3fc64fcfc3c7702dfc07b72a00cec9d5/server/consumer.go#L1627

And furhter on AckAll of seq 100 we delete all record of redeliveries <=100 meaning NumRedelivered will be 0 when you ack the final message

https://github.com/nats-io/nats-server/blob/c91f0fec3fc64fcfc3c7702dfc07b72a00cec9d5/server/consumer.go#L1640-L1644

This seems wrong to me, so I think we first have to agree on what NumRedelivered is supposed to mean.

**Comment by ripienaar** [comment]
@derekcollison need some clarification on what the redelivered feature is supposed to mean

**Comment by derekcollison** [comment]
IIRC NumRedelivered is the current outstanding messages that have deliver count > 1.

**Comment by derekcollison** [comment]
Once they are acked they are cleared.

**Comment by ripienaar** [comment]
That's indeed the current behavior, I can't see how thats useful? It would be much more useful to be able to see a particular consumer has a large and growing number of redeliveries seen over time as a rate of redelivery per second or similar.

**Comment by aricart** [comment]
I would expect redeliveries to be a stable metric that only grows over time. Then depending on monitoring frequency, it could be determined how many messages were resent. For the test I copied above, I was interested in verifying that redeliveries took place, however, the server was not able to answer that question.

**Comment by aricart** [comment]
From the discussion above, the current redeliveries number is just messages that have failed to process - the question then becomes is a per-message attempt or a count of messages that required redelivery

**Comment by derekcollison** [comment]
Feel free to propose updates if the behavior does not work correctly or is named wrong.
As designed it works correctly, but as you both point out may not be as useful as it could be.

**Comment by ripienaar** [comment]
In that case, my vote is that the redelivered field be turned into a count of redeliveries that never goes down.

**Comment by derekcollison** [comment]
Feels more aligned to things like num_pending that get adjusted and are a snapshot of the current state vs a counter.

**Comment by ripienaar** [comment]
Pending clearly is a number that represents a state in time - there is no benefit of a pending number that never decrease - all messages are at some point pending. So a snapshot it the only thing that makes sense for pending.

Perhaps we can do this, we adjust num_redelivered as proposed to be a total for the life of the consumer and add a pending_redeliveries (or something like that) that exhibits the current behavior?

**Comment by derekcollison** [comment]
Possibly, would want @kozlovic to weigh in since technically would be a breaking change. Just would want to assess risk.

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
