### ISSUE TITLE
Docs describing K/V Store disappear

### ISSUE THREAD

**Issue by wilstoff** [nats-io/nats-server#2659]
On 10/29 i was reading through some of the Jetstream docs and noticed the K/V store as a new feature that would be interesting to take advantage of.  Today however I can not find anything related to Key/Value store on the docs website, and i can't even find the picture i took below (was mostly letting people know we were going to have to migrate STAN -> jetstream in the future).  Did some docs update get rolled back?  I believe it should have been on the main Jetstream page https://docs.nats.io/jetstream/jetstream 
![image](https://user-images.githubusercontent.com/1379634/139701832-7c626f2b-fa37-4863-95b9-78058af432ae.png)

**Comment by ripienaar** [comment]
Not sure what happened with that, here are some up to date links though:

The `nats.go` package has a implementation of the KV, see here https://pkg.go.dev/github.com/nats-io/nats.go#KeyValue

Out other supported languages are all getting it, you can read about the internal design of the system here https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-8.md

And nightlies of the CLI has full access to it.

**Comment by jnmoyne** [comment]
Apologies for the confusion: there is a new version of the documentation that is currently being worked on and as the result of a GitHub mistake a preview (meaning it is still work in progress and not yet ready for release) of that version of the documentation was up on the docs.nats.io web site for a few hours on 10/29, which you were looking at. This mistake was reverted after a few hours and the docs website is now back to being the 'current' content, which is why some things you could see for a few hours at the time you were looking are now not visible anymore.

This new version contains a lot of changes from the current version of the docs including about the new KV functionality on top of JetStream and a reminder that JetStream now replaces STAN which is now legacy.

These changes will re-appear in the documentation once this new version of the doc is ready and gets pulled into the doc web site (for good).

**Comment by jnmoyne** [comment]
Note that the notice of deprecation of STAN is there in the current version of the docs at https://docs.nats.io/nats-streaming-concepts/intro#warning-deprecation-notice

**Comment by jnmoyne** [comment]
Well one way to look at the whole episode of that un-intended merge is that it’s encouraging to see it was only up for a few hours and yet this guy learned something he didn’t know and wanted to share with others just from one of the many changes I did, and he’s already asking "hey I want the new docs back!" :). I closed it because it will happen as part of final PR from my fork back to the natsio docs repo.

**Comment by wilstoff** [comment]
Thanks for the explanation, i was hoping it was something like that and not just me going crazy.  I think i noticed because it was such a drastic change in structure (STAN docs were hidden) that i felt i needed to read all about Jetstream.
