### ISSUE TITLE
Websockets add path for proxy

### ISSUE THREAD

**Issue by bfoxstudio** [nats-io/nats-server#2680]
## Feature Request
Add websocket /path in nats-server.

#### Use Case:
Use proxy https to http with path like nginx
wss://host:12345/nats-server

#### Proposed Change:
add o.path in
https://github.com/nats-io/nats-server/blob/main/server/websocket.go#L1081

**Comment by kozlovic** [comment]
Please help me understand what you are trying to do right now. Your client connects to `wss://host:port/nats-server` that points to nginx and then nginx creates a connection to `ws://<possible different host>:<possible different port>/nats-server`? (maybe the path `/nats-server` is not used to create the the server)

Your client originally connects to `wss://host:port/nats-server`, correct? The code you point to is really only used for cases where there is a NATS cluster of servers and the connect URLs of the various servers in the cluster will then be communicated to clients asynchronously. So the client library would then receive other servers `host:port` and complete the list for reconnect cases.
Adding a `path` to the urls returned by the server would then apply to all client libraries (assuming they are not parsing host/port and only using that), but another approach would be an option in the client to append a path prior to connect (but then that means doing that for all client libraries that support websocket).

Note that the server currently use the `path` of a websocket URL to determine if a connection is from a client (no path) or a leafnode, and in the future MQTT. So that could be an issue, or at least we would need to formalize what the option `path` values are acceptable (exclude or reserver some for internal purposes).

**Comment by bfoxstudio** [comment]
client connect from Inernet o  wss://host.com:port1/proxy_nginx_path
nginx redirect to ws://host_locla_company_network:port2/proxy_path

I made a mistake. we need fix nats.go client library
https://github.com/nats-io/nats.go/blob/main/ws.go#L563
	**ustr += u.Path**

i create issue in nats.go
https://github.com/nats-io/nats.go/issues/859

pls close this thread
