### ISSUE TITLE
done nats support priority queue？

### ISSUE THREAD

**Issue by jinjiang2009** [nats-io/nats-server#2728]
done nats support priority queue？our services need priority set，so，who can tell me about this question。

**Comment by derekcollison** [comment]
Could you describe the use case with a bit more detail?

**Comment by c16a** [comment]
@derekcollison I guess this is something we could use as well. Within a subject, can we set `priority` at the message level, so that when a few high priority messages are in the queue, they get precedence over low priority ones?

### Push-based consumers
The server must be able to decide on what _next_ to push to the subscribed client, given the bulk of undelivered messages that the client / client group is eligible to receive.

### Pull-based consumers
The NATS clients (libraries) should be able to check whether there are any high priority messages pending and consume them first.

In retrospective, I think this can idiomatically achieved by simply publishing to two topics - `feed.high` and `feed.low`.

**Comment by jinjiang2009** [comment]
> Could you describe the use case with a bit more detail?

In the same queue，we want have a label for example weight to tell us ，this message to be first deal；also as c16a mentioned ：Within a subject, can we set priority at the message level, so that when a few high priority messages are in the queue, they get precedence over low priority ones。
Like in rabbitmq，they support priority queue。

**Comment by c16a** [comment]
@jinjiang2009 Is there an issue with using two different subjects for this purpose? Unlike RabbitMQ and Kafka, it's extremely cheap and memory efficient to create a new subject.

**Comment by jinjiang2009** [comment]
> @jinjiang2009 Is there an issue with using two different subjects for this purpose? Unlike RabbitMQ and Kafka, it's extremely cheap and memory efficient to create a new subject.

First，this is a good idea to use different subject to slove the problem. But our team want it like a max heap that can auto order the message.

**Comment by derekcollison** [comment]
We do not have priorities in JetStream and at this time we do not have plans to implement.

Some suggestions, you could use headers and do client side filtering etc. Using NAK for the ones you do not want, etc.
You could also break up the priorities, say you want 10 into separate streams and have the client check the higher priorities first.

**Comment by derekcollison** [comment]
Will close this but will re-open as needed.

**Comment by jinjiang2009** [comment]
> We do not have priorities in JetStream and at this time we do not have plans to implement.
> 
> Some suggestions, you could use headers and do client side filtering etc. Using NAK for the ones you do not want, etc. You could also break up the priorities, say you want 10 into separate streams and have the client check the higher priorities first.

Thanks.
