### ISSUE TITLE
Leaf Node ignores `ca_file` settings

### ISSUE THREAD

**Issue by mcosta74** [nats-io/nats-server#2868]
Hello, 

I have a custom CA and, following the documentation I'm able to connect to my server using both Python and C library.

I now have problem authenticating a leaf node using the CA certificate

here my configuration

**SERVER**
```
isten: 0.0.0.0:4223

CERT_FILE: serve.crt
KEY_FILE: server.key
CA_FILE: ca_file.crt

tls {
  cert_file: $CERT_FILE
  key_file: $KEY_FILE
  ca_file: $CA_FILE
  verify: true
}

leafnodes {
  port: 7422

  tls {
    cert_file: $CERT_FILE
    key_file: $KEY_FILE
    ca_file: $CA_FILE
    verify: true
  }
}
```

**LEAF NODE**
```
listen: "0.0.0.0:4112"

CERT_FILE: server.crt
KEY_FILE: server.key
CA_FILE: ca_file.crt

leafnodes {
  remotes: [
    {
      url: "tls://<server>:7422"
    }
  ]

  tls {
    cert_file: $CERT_FILE
    key_file: $KEY_FILE
    ca_file: $CA_FILE
    verify: true
  }
}
```

now when I run both I'm getting
```
[35701] 2022/02/14 11:07:52.247561 [ERR] 192.168.0.104:7422 - lid:41 - TLS leafnode handshake error: x509: certificate signed by unknown authority
```

so looks like the leaf node doesn't use the `ca_file` settings

**Comment by kozlovic** [comment]
Your LEAFNODE configuration is wrong. This one is the one that tries to connect to the SERVER configuration, so the remotes[] section should contain the tls configuration, as such:
```
leafnodes {
  remotes: [
    {
      url: "tls://<server>:7422"
      tls {
         cert_file: $CERT_FILE
         key_file: $KEY_FILE
         ca_file: $CA_FILE
     }
    }
  ] 
}
```
Notice I removed the `verify: true` in that section because it does not apply. This parameter is for the "server" side, the one that accepts the connection. This parameter indicates that the server will require that the client presents a certificate.

**Comment by mcosta74** [comment]
thanks,
