### ISSUE TITLE
Account max subscriptions do not appear to be honored

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-server#2889]
#### Versions of `nats-server` and affected client libraries used:
main branch, commit ab2b9f3fbf1f099b678c832aa76d6835e7be3952
nats cli (devel - main branch today)

#### Steps or code to reproduce the issue:
```text
 $ cat sub_limit.conf 

accounts : {
     A: {
        limits {
            max_subscriptions: 1
        }
        users: [
            {user: a, password: a}
        ]
    }
}
```

Run the NATS server:
```bash
nats-server -c sub_limit.conf 
```

Launch subscribers:
```text
$  nats sub foo --user a --password a &
$  nats sub foo --user a --password a &
$  nats sub foo --user a --password a &
```

... all succeed...

Publish a message:

```text
 $ nats pub --user a --password a foo hello
[#1] Received on "foo"
hello

[#1] Received on "foo"
hello

[#1] Received on "foo"
hello

16:43:46 Published 5 bytes to "foo"
```
#### Expected result:
Either a subscription error from the 2nd and 3rd subscriptions, or at least only the first subscription received the message.

#### Actual result:
All three subscribers received the message.

**Comment by derekcollison** [comment]
That limit is per client connection not per account, so since you use the NATS cli they are all independent clients. If you did a test with same client and did the second sub you would get cut off. I wrote the test just now.

Not sure that is the right behavior, seems like it should not be fatal.

Also I agree that setup feels like should be max per account so will investigate a bit more..

**Comment by derekcollison** [comment]
Looking back yes that limit is per connection not for the whole account. Not sure we can enforce per account on a scale something like NGS.
