### ISSUE TITLE
Client occasionally incorrectly assigned to global account

### ISSUE THREAD

**Issue by smlx** [nats-io/nats-server#2926]
## Defect

Occasionally a client which is supposed to be in a specific account is added to the global `$G` account instead.

This is visible in the trace log because when the client is correctly added to the account (`lagoonRemote` in this example) you can see the subscription propagated to connected nodes with a trace like this after the client connects:

```
->> [RS+ lagoonRemote lagoon.sshportal.api sshportalapi 1]
```

However sometimes you see a trace like this:

```
->> [RS+ $G lagoon.sshportal.api sshportalapi 1]
```

Because this seems to be some kind of race condition, I haven't nailed down the exact scenario when it happens. However I've got an environment where it is reliably reproducible. See the link below to a repository containing a `docker-compose` environment which you can run locally to reproduce the problem. That repository contains the full `nats.conf`.

 - [x] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

Server:

```
mre-nats-0-1  | [1] 2022/03/16 15:58:07.153560 [INF] Starting nats-server
mre-nats-0-1  | [1] 2022/03/16 15:58:07.153594 [INF]   Version:  2.7.4
mre-nats-0-1  | [1] 2022/03/16 15:58:07.153597 [INF]   Git:      [a86b84a]
mre-nats-0-1  | [1] 2022/03/16 15:58:07.153601 [DBG]   Go build: go1.17.8
```

Client:
```
~ # nats --version
0.0.28
```

#### OS/Container environment:

Docker container `nats:2.7.4-alpine3.15` (server).
Docker container `natsio/nats-box:0.8.1` (client)

#### Steps or code to reproduce the issue:

1. Check out this repository: https://github.com/smlx/nats-mre
2. Run `docker-compose up -d; ./find.bug.sh`

#### Expected result:

Client is always added to the `lagoonRemote` account.

#### Actual result:

Client is occasionally added to the global `$G` account.

**Comment by kozlovic** [comment]
@smlx Thank you for the report and repo to reproduce the issue. This is helpful. Will let you know what we find as soon as possible.

**Comment by kozlovic** [comment]
@smlx We have identified the issue and working on a fix (but not sure yet what it will be). The issue is that you have duplicated the user name in both authorization{} and accounts{} block. The parsing is non-deterministic (even if your config file has one before the other, internally it will be parsed in random order). So this results internally in user that will either be part of the account{} (the working case) or is parsed last as part of authorization{} that is not associated with any user and therefore bound to $G.

The expectation was that people using accounts{} would not be configuring users in authorization{} (since the user can be fully configured - with permissions and all - in the accounts{} block). But clearly, the server did not reject that, causing this weird behavior.

For now, I would recommend that you move the configuration of the users inside the accounts{} block and get rid of completely of the authorization{} block. Should you define some auth time-out, you can keep it, but do not set any user name inside.

The next release will reject your configuration, but we are not sure yet if we are going to just look for duplicate user definitions, or reject any user configuration (duplicates or not) in authorization{} if accounts{} is specified.
