### ISSUE TITLE
[JS] $JS.API.CONSUMER.MSG.NEXT.<stream.<dur> 404 status instead of JS api error

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#3093]
## Defect

> PUB $JS.API.CONSUMER.MSG.NEXT.stream.durable _INBOX.5LDA8A1PB37F1C38S0ZZUO 38␍␊{"batch":1,"no_wait":true,"expires":0}␍␊
> HMSG _INBOX.5LDA8A1PB37F1C38S0ZZUO 2  28 28␍␊NATS/1.0 404 No Messages␍␊␍␊␍␊

The JS API call above can return a status of 404. This is unexpected because it is a JS API call that should be in an API info response. Clients (assuming they all have the same bug) will parse the status, and resolve this call as an error early (in on nats core request handling), when the error should be deferred to the JS API layer. This results in clients either re-writing the error.

Instead the API call should behave more like other JS API calls:

 > MSG _INBOX.5LDA8A1PB37F1C38S0ZYUW.5LDA8A1PB37F1C38S100CK 1 127␍␊{"type":"io.nats.jetstream.api.v1.stream_info_response","error":{"code":404,"err_code":10059,"description":"stream not found"}}␍␊

**Comment by kozlovic** [comment]
Actually, in other libraries, the library does check for headers and possible error status before passing the error back to the user. In this case, since you pass "no_wait", the server correctly returns you a 404 to indicate that there are no messages (well, assuming there are really no messages ;-))
