### ISSUE TITLE
Messages seemingly dropped when purging stream, even with ack enabled

### ISSUE THREAD

**Issue by yentheo** [nats-io/nats-server#3106]
We are using NATS as our Event bus/Messaging bus. I was seemingly experiencing some race conditions. 

I'm not a 100% sure if this is the correct place to share this, if not, just let me know.

We have set up something among the lines of the following. 

There is a backend system that creates entities, with unique id's and publishes that to subjects with a name like 'entities.{id}'. Now subjects that begin with 'entities.>' are part of a configured jetstream on our NATS server.

We have frontend system (JavaScript) that connects to the same NATS server and subscribes to 'entities.*'. Here we do some custom logic with RxJS to get an observable that emits an array of all the entities every time something changes.

If an entity gets deleted, we publish an empty message on that subject. The logic on the frontend side removes the entity from the array. Because we don't want the NATS server to get cluttered with unused subjects, we also purge that specific subject on the backend.
e.g.
```
con.Publish('entities.1', { id; 1 });
con.Publish('entities.2', { id: 2 });
```
on the backend, will result in:
```
[{ id: 1 }, { id: 2 }]
```
on the frontend.
This seems to be working great. But after a delete like so:
```
con.Publish('entities.1', null);
jsmc.Purge(streamName, 'entities.1');
```
Most of the times we get the expected result:
```
[{ id: 2 }]
```
But sometimes that "empty" message is not received by the client. To remove any chance that the fault is in our client code, I made this small repro project: https://github.com/yentheo/nats-problem-reproduction

There is a readme in there on how to run it.

If we don't do the purge, it works as we want it to work, but our server get's cluttered with empty subjects.

Are we using the JetStreams wrong, are we using NATS wrong, or do we just need some tweak or adjustement?

Thanks in advance.

**Comment by derekcollison** [comment]
You might want to look at KV. Also seems this is just a timing thing. Might be worth putting delay of say 250ms between the empty publish and the purge call.

**Comment by derekcollison** [comment]
The KV abstraction for JetStream.

The issue you are seeing is that by the time a consumer is processing any new messages, both the new message and the purge could have been processed, and hence you won't receive the message. The stream processing and consumer can run concurrently.

We are looking into some things to have reliable processing when messages are expired or removed due to limits, but nothing definitive yet.

**Comment by yentheo** [comment]
Thanks! Will definitely take a look at the KV Abstraction. And we assumed it would be something of a race condition with the purge and the publish. Thanks for the confirmation.

**Comment by kozlovic** [comment]
@yentheo I was going to comment but Derek beat me to it. You can imagine the processing on incoming JS messages happening in one thread and the distribution from the consumer happening in the second.

When you publish the message, and by the way, in your reproduction code, you seem to be using bare NATS, not a JS context to publish the message, which means that the library does not wait for a pub ack back from the server, the message is added to the stream and the server "notifies" the matching consumers that there is a new message available. But right after you send a purge request (and again, since you use the bare NATS publish for the message, it is very likely that the purge request is going to be processed quickly after the published message), which means that there is a possibility that the purge request is processed before the second thread (the consumer delivery routine) has a chance to run. If that happens, even though the consumer was notified that there was something, it will realize that there is nothing and go back to "sleep".

If there was only 1 consumer of this message, I could say that you need to reverse roles and let the consumer of that "nil" message issue the purge: basically, after it has received notification that it was the last, it can purge. If conceptually, the front-end should not be able to use administrative requests (purge), then it could send to another dedicated stream indicating which subject can be purged. The backend would have a consumer on that stream and issue the purge.
But of course, the above does not work if you have more than 1 front-end consumer, since the first to consume that nil message would cause the purge and the other consumers would be back to that race of possibly missing the nil message.

With all that said, I hope you understand better what is happening and may be able to come up with a solution that works for you.

**Comment by tpihl** [comment]
From an event sourcing perspective you may also introduce a parallel subject (and have clients make a consumer that get both both on the client side). 

Then an deletedentity.1 can be picked up by all clients and handled correctly. You can purge entity.1 right away without regards to syncing since the deleted information will still be there. And then run a cleanup purging deletedentity.* for older than x (all depending on how fast/often you need to clean those up. 

I don’t know how long your clients may live or how far behind they are allowed to be, any purging may need to consider if there may be cornercases there.

**Comment by yentheo** [comment]
@kozlovic Thanks for your explanation. I just tried it with publishing via a JS context, seems like that makes it very stable. 
I changed the publish code to:
```
IConnection c = cf.CreateConnection(options);
var jsmc = c.CreateJetStreamManagementContext();
var jsc = c.CreateJetStreamContext();
for (var j = 0; j < 1000; j++)
{
    var subject = $"test.{j}";
    await jsc.PublishAsync(subject, new byte[0]);
    jsmc.PurgeStream("test", new PurgeOptionsBuilder().WithSubject(subject).Build());
}
```

And I receive every message. Seems like I just should be doing that.

Thanks!

**Comment by kozlovic** [comment]
@yentheo But to be clear, you are just reducing the chances for the race, but the race still exists.
