### ISSUE TITLE
Is there a recommended system configuration for deploying nats and jetstream

### ISSUE THREAD

**Issue by Doslin** [nats-io/nats-server#3643]
Is there a recommended system configuration for deploying nats and jetstream
For example: [TiDB Environment and System Configuration Check](https://docs.pingcap.com/tidb/stable/check-before-deployment)

**Comment by bruth** [comment]
Hi @Doslin. Depending on the level of detail you want, here is a good starting point: https://docs.nats.io/running-a-nats-service/introduction/installation.

There are other pages in the docs specific to Docker or [Kubernetes](https://docs.nats.io/running-a-nats-service/nats-kubernetes) for example as well. Another useful page is the [environment considerations](https://docs.nats.io/running-a-nats-service/environment) which talk about a few more details like virtualization.

In general, running a server should as dead simple as possible (by design). Depending on the environment you are deploying to (e.g. cloud) and the workload you expect to run, performance considerations of the disk (JetStream) and the network bandwidth need to be considered.

Please let us know if there are specific additional details that would be useful in the docs, we are actively revamping them so feedback is welcome.
