### ISSUE TITLE
Questions about num_routes for NATs server

### ISSUE THREAD

**Issue by chichunhua** [nats-io/nats-server#3765]
Hi there,

Hope everything is going well at your end. 

I am new to NATs and have few questions, hope someone who knows it could give me some hint and clue. 

I am using core NATs, in the cluster I have 3 NATs services,  the monitoring endpoints shows the num_routes are 3 too. However, at some point, the routes are down, not showing in the monitoring endpoints, and it won't come back too. I am trying to debug it to see what cause it, why it happens but no clue at all. 

1. was this reported before? is there anything going on relates to this?
2. the services are still running, but num_routes are not showing them. what could cause it? 
3. I can fix it with restart the services, is there a way that can bring it back automatically?

Looking forwards your kind reply.
Thanks!

**Comment by wallyqs** [comment]
Hi @chichunhua if you have a cluster of 3 nodes then you would see a `num_routes: 2` being reported since those are the connections against the other 2 nodes, so that would be the normal value. Maybe while the cluster is being formed one of the nodes may 'auto discover' itself but then this connection is pruned during the startup (a message logging `Router connection closed: Duplicate Route`). Is that what you are seeing or are you seeing values less than 2? Are you using latest version?

**Comment by chichunhua** [comment]
@wallyqs thanks for the quick reply. I actually has 4 services, 1 as seed and 3 as slave/workers. They were work find before some point, and then they coming down. the `num_routes` only showing 0 or 1 now. It's pretty tricky because I deployed them to different zones in same cloud, 1 zone works fine, and this happens to the other one.  I am using 2.0.4 version currently, and wondering if you had this issue before and fixed it in any version that I can use.

**Comment by wallyqs** [comment]
Could you share some examples of how you are setting up the DNS for the nodes? Do all the nodes have their own A record? Are you setting `cluster_advertise`? There is also an option `connect_retries` to increase the number of attempts to connect to discovered routes from the seed.

**Comment by chichunhua** [comment]
1. yes, they all have their onw A record but same name.
2. the setting is default one, only specified the port number. 

what is `cluster_advertise` for? do you mind point me to the config variables? I saw lots of config regarding `STAN` and `JetStream` though.  

I found this in version 2.3.0, it mentioned that `Failed route TLS handshake would leave the failed connection's lock in a locked state (https://github.com/nats-io/nats-server/pull/2305)`. could it be also one of the reason cause the issue?

**Comment by wallyqs** [comment]
@chichunhua it could be related, so definitely recommend to upgrade to latest. You can find info about the cluster config here: 
https://github.com/nats-io/nats.docs/blob/c08a4b0baf1d93e762cec2d72ee86021d9674561/running-a-nats-service/configuration/clustering/cluster_config.md#L12
When using the seed mode setup, you need to advertise a different hostname/A record for each one of the nodes otherwise you could get partitions or may not try to reconnect if the names are the same.

**Comment by chichunhua** [comment]
Thank you! @wallyqs

**Comment by derekcollison** [comment]
Closing for now but feel free to re-open as needed.
