### ISSUE TITLE
If only one NATS cluster is down, it becomes unavailable

### ISSUE THREAD

**Issue by marload** [nats-io/nats-server#4003]
I am using helm to deploy NATS on k8s and have a 3 node cluster.
The moment one of the nodes goes down, the rest of the NATS is inaccessible.
Is there something I am misunderstanding about the cluster availability of NATS?

```
$ nats str ls
nats: error: could not list streams: JetStream system temporarily unavailable (10008)
```

**Comment by ripienaar** [comment]
Is your stream configured to have 3 replicas? Show stream info.

**Comment by ripienaar** [comment]
Sorry, my bad - can yoiu please show `nats server report jsz` not about the individual stream.

**Comment by wallyqs** [comment]
You could get JetStream unavailable errors when a node detaches from the cluster due to re-elections and reconnects, but generally this should be temporary as the error reports, for publishing messages whenever there is a 503 / no responders errors default retry that waits 250ms before sending the message again after it got an error, though we do not do this for other APIs at the moment but same could be done: https://github.com/nats-io/nats.go/blob/main/js.go#L208

**Comment by bruth** [comment]
@marload One server in a three node cluster should not make the other two servers unavailable. There would be something else going on.

Given the lack of activity, I am closing, but feel free to reopen if there are still questions or concerns.

**Comment by Badabum** [comment]
I'm expriencing the same issue - have a 3 node cluster (v2.12.0) running on 3 instances of Azure Container Instance, when updating the cluster each node get "replaces" but only 1 at a time. When 1 node is gone, Jetstream becomes unavailable always. Which is quite weird since the clustering should be for HA scenarios, and 1 node going down in 3 node cluster should not make the whole JS system unavailable.

**Comment by neilalexander** [comment]
@Badabum How do you "replace" nodes exactly? Do they come up with the exact same server config and the same volume for their `store_dir`?

Please also use the CLI to check `nats server report jetstream` in the system account and see how many nodes it believes are in the meta group.

**Comment by Badabum** [comment]
Hey @neilalexander thx for reply! The replace in case of Container Instances is shitty - it just kills the contianer, what's worse with SIGTERM not SIGINT, so that's once side of things. Regarding configuration - yep, it's the same config and volume mounts, storage directories all the time. 
But your suggestion `nats server report jetstream` actually identified the issue - it believed there are 4 nodes (1 gone, not seeing) in the cluster. So perhaps that's the root issue. In any case, I migrated our nats setup to k8s since my post and so far it's smooth experience

**Comment by neilalexander** [comment]
In this situation, you should use `nats server cluster peer-remove` to tell the system that the dead node is never coming back again, which will shrink the cluster down to the right size and will fix the quorum needed count.

Keep in mind that quorum needed is `(cluster size/2) + 1`, so if the system believes there are meant to be 4 nodes, but one is permanently dead and you take down another during the upgrade, that leaves only 2 out of 4 nodes remaining, which is not enough to satisfy quorum needed of 3.

By `peer-remove`-ing the fully-dead node, you'll reduce the cluster size from 4 to 3, which brings quorum needed down to 2 instead of 3, so you can once again tolerate taking one node down during upgrades.

**Comment by Badabum** [comment]
@neilalexander hey, thanks for the explanation! will keep in mind
