### ISSUE TITLE
What makes NATS a better choice for the backbone of RPC than other MQs?

### ISSUE THREAD

**Issue by GingerMoon** [nats-io/nats-server#4375]
Are there any design tradeoffs that make NATS a better backbone for rpc than other MQs?
I checked https://docs.nats.io/nats-concepts/core-nats/reqreply but don't see the tradeoffs NATS made which makes it a better choice than other MQs.
And are there any benchmarks comparing the performance of several pupular RPC frameworks?

**Comment by jnmoyne** [comment]
With NATS you can do either 'interactive' request/reply using Core NATS, or using JetStream you can do more 'CQRS' style of request/reply (meaning you publish the request message into a stream (working as a queue) and the reply message is published by the server(s) into another stream. 

In one case (Core NATS request reply) you send a request and expect a reply or you have to send the request again (meaning the request call returns either the reply message or a timeout error). NATS easily allows you to distribute those requests using a 'queue-group'. On top of it, when using a NATS SuperCluster the request-reply functionality also provide 'geo-affinity' of the processing of the requests: if the request application is connected to a cluster, and there is one (or more) instances of the service running in that cluster then the requests are directed to the these 'local' instances of the service.

Using JetStream to do request-reply on the other hand is like submitting a job to a job queue (this is possible in JetStream because (unlike other streaming systems like Kafka for example) you can set a stream to behave as a 'working queue'), and then creating a filtered consumer on a separate reply queue to find the replies to your specific queries. It means that for example the requesting application could publish the request, and then get disconnected or shut down for a while and restart or reconnect much later and still be able to retrieve the reply message(s).

As far as performance goes, it's easy to measure it using `nats` (e.g.  with `nats bench --reply` and `nats bench --request`) to do synchronous Core NATS request-reply benchmarks (you can easily calculate the average latency by taking the invert of the number of request/reply operations per second as reported by `nats bench`). See `nats cheat bench` for some examples of how to use it.

**Comment by GingerMoon** [comment]
Thanks a lot @jnmoyne for the reply! It's helpful.
I would appreciate if you could also share some deeper insights about the design tradeoffs which makes NATS a better choice for the RPC backbone than other MQ implementations. 

My understanding is, NATS acts a middle man between the service provider and the consumer. 
So compared to the way of consumer connecting directly to provider, the only overhead is the extra network cost between NATS and the service provider and the service consumer. For example, no extra cost for persistenting messages(the RPC requests), no extra message replication to broker replicas, broker pushes request directly to the subscribers(both providers and consumers).

Please correct me if I am wrong.

**Comment by derekcollison** [comment]
The biggest advantages from my perspective are the following.

1. NATS topology, you can create a micro-service and run it at scale on any NATS system with any topology, including multi-region, multiple cloud providers or out at the edge with no additional components needed, e.g. Load balancers, VPCs, firewalls GSLBs, Service Mesh  or API gateways.

2. Location independent scale out. Just run more instances, no step 2.

**Comment by jnmoyne** [comment]
> So compared to the way of consumer connecting directly to provider, the only overhead is the extra network cost between NATS and the service provider and the service consumer. For example, no extra cost for persistenting messages(the RPC requests), no extra message replication to broker replicas, broker pushes request directly to the subscribers(both providers and consumers).

When using core NATS request-reply the above is correct, and in return you get transparent (to the client application) distribution of the requests to achieve horizontal scalability, location independence (with geo-affinity when using SuperClusters), no need to use any kind of load balancer, DNS trickery, proxies, API gateways, or sidecars.

**Comment by GingerMoon** [comment]
Thanks a loooooot guys for sharing the insight! 
I am closing the ticket.
