### ISSUE TITLE
[JS] [subject transforms] - sourced streams that apply a transform, don't have the transform applied on creation

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-server#4636]
### What version were you using?

v2.10.1 and v2.10.2-RC.14

### What environment was the server running in?

github actions and os x

### Is this defect reproducible?

```javascript
  const proms = ["foo", "bar", "baz"].map((subj) => {
    return jsm.streams.add({
      name: subj,
      subjects: [subj],
      storage: StorageType.Memory,
    });
  });
  await Promise.all(proms);

  const js = nc.jetstream();
  await Promise.all([
    js.publish("foo", Empty),
    js.publish("bar", Empty),
    js.publish("baz", Empty),
  ]);

  await jsm.streams.add({
    name: "sourced",
    storage: StorageType.Memory,
    sources: [
      { name: "foo", subject_transforms: [{ src: ">", dest: "foo2.>" }] },
      { name: "bar" },
      { name: "baz" },
    ],
  });

  while (true) {
    const si = await jsm.streams.info("sourced");
    if (si.state.messages === 3) {
      break;
    }
    await delay(100);
  }

  const m = await jsm.streams.getMessage("sourced", { seq: 1 });
 // this assertion will fail
  assertEquals(m.subject, "foo2.foo");
```

### Given the capability you are leveraging, describe your expectation?

for the subject to be transformed from `foo` to `foo2.foo`

### Given the expectation, what is the defect you are observing?

the subject on the sourced stream remains at `foo`

**Comment by jnmoyne** [comment]
It could be that the test fails because the first message in "sourced" is not the message coming from stream "foo". Since this is 3 separate sources there is no guarantee that the order in which the messages are sourced is the same order in which they were initially published (especially here as you do the publish to the 3 streams being sourced back-to-back).

So the message transformed to "foo2.foo" may not necessarily be the first one in "sourced" as this code expects, it could be the second or even the third message.
