### ISSUE TITLE
Embedded NATS Connectors

### ISSUE THREAD

**Issue by laugimethods** [nats-io/nats-server#496]
- [X] Feature Request or Change Proposal

#### Use Case:
It would be helpful to be able to connect NATS directly to external systems like Cassandra, Camel, etc. instead of relying on _ad hoc_ bridges or external connectors.
 
#### Proposed Change:
Integrate into the NATS Server a set of plugins that can be configured to read or write messages from/to external systems.
Those plugins could be inspired by https://hub.docker.com/_/telegraf/
 
#### Who Benefits From The Change(s)?
Anyone who needs to connect heterogeneous systems through NATS.

#### Alternative Approaches
Dedicated (external) NATS Connectors or Telegraf.

**Comment by ColinSullivan1** [comment]
Do you mean into the NATS server itself, or as part of the NATS server docker image?  IMO a cleaner approach could be for NATS to provide docker images that include the NATS server with various connectors or exporters, for example, NATS + Prometheus in one image.

**Comment by laugimethods** [comment]
I'm suggesting the integration -  internal to NATS server itself - of plugins to avoid external pull (from NATS) / push (to whatever) or pull (from whatever) / push (to NATS). 
Like I had to do to store NATS messages into Cassandra ( https://github.com/Logimethods/smart-meter/blob/master/dockerfile-cassandra-inject/go/src/app/main.go - forgive the code, that was my first tentative with that language -).  
So to be more robust and efficient.
Those plugins should be optional and configurable. Docker images preconfigured would be of course welcome, but I don't know if it's feasible since those plugin will need to be configured (DB url, etc.).

**Comment by ColinSullivan1** [comment]
@laugimethods , Always good to see NATS bridging with other technologies!

I can see the merits of this, although this would stray from the NATS tenets of simplicity and performance.  We feel strongly that this type of functionality remain external to the server.

Along these lines, if you look at the NATS streaming server, we actually [embedded](https://github.com/nats-io/nats-streaming-server/blob/v0.5.0/server/server.go#L967) the NATS server rather than do a direct integration of those features.

IMO the better approach for NATS may be to invert this (the alternative approach) - a golang based connector plugin infrastructure that optionally starts an embedded NATS server that is connected internally over loopback. 

It'd be a new component to NATS, but would give a lot more flexibility in design/architecture by avoiding concern around affecting simplicity, performance, or security in the core NATS server.

We really appreciate you starting this discussion... Does this make sense?

**Comment by AshfordN** [comment]
I agree that connecting through an internal interface would be beneficial for services that are meant to be tightly coupled with their underlying communication system, but at the same time, I also understand that this would introduce some level of added complexity.
It's a feature that I would like to see, but I still think we need to discuss it more, since it touches on some core principles of NATS.

**Comment by OneCricketeer** [comment]
Why not use Benthos?
https://www.benthos.dev/docs/components/inputs/nats/

IMO, don't bloat a product, let each indicia product do one thing well, and for NATS, that's streaming, not ETL integration
