### ISSUE TITLE
`nats: context deadline exceeded` error when reaching a large number of consumers around 50-60K consumers.

### ISSUE THREAD

**Issue by VuongUranus** [nats-io/nats-server#5609]
### Observed behavior

I am using nats jetstream for my distributed chat system. My structure is simply to create a consumer corresponding to a chat channel for a connected user. In terms of message speed, it is great, however when the number of consumers increases to a threshold ranging from 50-60K consumers, I constantly get the error `nats: context deadline exceeded`. I checked the hardware like CPU and memory and found it to be completely normal. Where does the problem come from?

### Expected behavior

I want to be able to scale as consumer creation increases as the number of users increases. Because I see that nats jetstream has great potential for a chat system.

### Server and client version

nats-server: v2.10.16

**Comment by derekcollison** [comment]
If those consumers are R3 that can cause issues as HA Assets run a full NATS Raft Group (NRG).

There are better approached to systems with high number of observables.

**Comment by VuongUranus** [comment]
Is there any way I can limit this error?

**Comment by derekcollison** [comment]
Can you share stream info and more information about how you are using consumers?

**Comment by VuongUranus** [comment]
Here is my thread configuration and consumer configuration
```go
		_, err = js.AddStream(&nats.StreamConfig{
			Name:        gocfg.CONFIG.NATS_STREAM_NAME,
			Subjects:    []string{gocfg.CONFIG.NATS_STREAM_SUBJECT},
			Storage:     nats.MemoryStorage,
			Retention:   nats.LimitsPolicy,
			MaxAge:      1 * time.Minute,
			MaxMsgSize:  5 << 20, // max single message size is 5 MB
			Discard:     nats.DiscardOld,
			Replicas:    3,
			AllowDirect: true,
		})
```

```go
sub, err := n.Subscribe(channelName, func(msg *nats.Msg) {
			f(msg.Data)
		},
		nats.DeliverNew()		
)
```

I use consumers to listen for messages from a chat channel in our chat system. For example, a user who is in 10 chat channels will create 10 cosumers to listen to messages from those 10 channels.

**Comment by derekcollison** [comment]
That design will probably not scale even if you made the consumers R1 and lighter weight.

**Comment by derekcollison** [comment]
I think there is a different way to approach this problem that can scale much better.

It would use a shared KV for where any given user is in a channel (last chat received, read status etc). Then the main channels can be all in one stream and use republish to allow simple NATS core subs to receive new chat messages. The headers in republished messages have enough information to know if you missed something and you can either use a quick ordered consumer to get the messages you missed or use direct get functionality to do so.

This would avoid the majority (if not all) consumers in this architecture.

**Comment by VuongUranus** [comment]
Thank you very much I will consider your solution to upgrade my system.

**Comment by VuongUranus** [comment]
Sorry, but may I ask more about the effect of KV in this new architecture? And what is the effect of using sub NATS Core and using republish? Thanks a lot!

**Comment by VuongUranus** [comment]
Can you show me an example of Republish in stream configuration?

**Comment by VuongUranus** [comment]
Sorry I don't understand what you mean.

**Comment by VuongUranus** [comment]
Sorry I still don't understand what you mean, can you explain it more clearly? And I need a specific example of republish. Help me please.

**Comment by jnmoyne** [comment]
JetStream consumers have state that has to be maintained by the NATS server(s) and therefore are not an "infinite" resource when compared to core NATS subscribers which can be very numerous. 

As a general rule with NATS you want to leverage subject based addressing as much as possible to keep the number of consumers (and streams) in check. In your case for example it would be more scalable to have a single stream with all the channels (in different subjects) and then one consumer per user which has a filter for each channel the user is interested in (eg 1 consumer with 10 filters) rather than 10 consumers.

And if your have a too large number of users (eg "hundreds of thousands") then you can get the next level of scalability by doing what @derekcollison explains above which is not use consumers at all but rather rely on the ability of a stream to republish the messages it ingest on a new Core NATS subject and have the clients to just listen on those core NATS messages (since you can have a very large number of core NATS listeners) in combination with using the stream get operation (to get the initial value messages when connecting or re-connecting).
