### ISSUE TITLE
Leaf Nodes Leak Internal IP's when using no_advertise: true

### ISSUE THREAD

**Issue by jseiser** [nats-io/nats-server#5723]

**Comment by kozlovic** [comment]
@jseiser I assume that the configuration you posted above is "yours", that is, the "hub" configuration, not the one from your customer, right? (Note, it looks like there are the same leaf user defined twice, I also assume that this is a typo when creating the mock configuration for the issue report).

You misunderstood the use of "no_advertise". This configuration is to not advertise a server's URL to *its* cluster. That is, say that you have HUB1 and HUB2, each has a LeafNode URL, the `no_advertise` means that HUB1 won't tell HUB2 what its LeafNode's URL is, and vice versa. Which means that if SPOKE1 connects to HUB1, it will not know HUB2's LeafNode's URL. This is similar to how `no_advertise` works in the `cluster{}` block. If a client connects to `HUB1`, it would not be able to reconnect to `HUB2` since `HUB1` would not know the client URL's of `HUB2`. Of course, if the client (or LeafNode) explicitly provides the URL to `HUB1` and `HUB2` in the connect API (or in `remotes[]` URLs list), then they can reconnect since they know explicitly the URLs of the servers.

Your issue is that your "hub" server as shown above uses `port: 7422`, which means `0.0.0.0:7422`, which means that it would listen to any interface at port 7422. When you run the server with `-D`, you should see what address is sent to the SPOKE server. 
But that in itself may not even an issue since the SPOKE server will connect only based on the URL the customer provides in the `remotes[]` section. If that URL is the "correct" IP, then the server will connect fine. However, if connection were to break, the SPOKE server would try to reconnect to any of the address in its "remotes" list in addition to the one(s) it received from the HUB's INFO protocol.

So you need to make sure to set the `listen: <IP that you want the customer to use>:<port>` so that the server does not have any other IP than that to send back to the spoke. If that IP that you want the client to connect to does not mean anything to the hub's server itself, you should use `advertise: <the IP that you want the customer to use>:<port>` (note, it is `advertise`, not `no_advertise`). The server will still accept connections based on the `listen` configuration (so there you could have the docker IP), but will send to the SPOKE the address specified in the `advertise` configuration.

Of course, the customer needs to have in its `remotes[]` URLs configuration the proper IP that allows it to connect to the LEAF or if a hostname, make sure that the name resolution does not return IPs that are not valid for your configuration.

So again, the `no_advertise` just makes a given server URLs not being shared within the cluster, not to its own clients/leaf nodes.

**Comment by jseiser** [comment]
@kozlovic  thanks for the reply.  The information you provided us unfortunate, because I *think* means that I will need to create a new `leaf` section for every single remote leaf.

Each `leaf client` is connecting through a DMZ, by hitting a LB, which is fronting HA proxy which in turn is sending to the IP of the server running each NATS container.

So each client, is pointing to a unique LB, with a unique DNS name.  client1-lb.com, client2-lb.com etc.  

So i think with what you are telling me, is i would need to do something like this

```

leafnodes: {
    port: 7422
    advertise: client1-lb.com:7422

    authorization {
        users = [
            {user: leaf1, password: $XX_LEAF_HASH, account: RAS}
        ]
    }
}

leafnodes: {
    port: 7423
    advertise: client2-lb.com:7422

    authorization {
        users = [
            {user: leaf2, password: $XX_LEAF_HASH, account: RAS}
        ]
    }
}
```

Is there no way to share this leaf, but stop trying to inform the already connected client how to connect.
