### ISSUE TITLE
Time duration for `handshake_first` option is not respected for leafnodes

### ISSUE THREAD

**Issue by mcosta74** [nats-io/nats-server#5772]
### Observed behavior

According to this [ADR](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-40.md) passing a time duration for the `handshake_first` option, makes the server backward compatible because after the timeout the server is supposed to use the standard TLS flow.

This works for standard connections (from clients) but not for leafnodes.
If the leafnode doesn't declare the `handshake_first` field in the `remotes` section, its connection will be never accepted by the server

I'm able to connect to my server using `nats-cli` with or without the `--tlsfirst` flag (because of the timeout) but the leafnode can connect to the server only if it use the field in the remote section.

### Expected behavior

A leafnode connection without `handshake_first` is accepted (standard TLS flow) after the initial timeout

### Server and client version

nats-server: v2.10.18 (both server and leafnode)
nats-cli: 0.1.5

### Steps to reproduce

Main server has this configuration
```
TLS = {
  cert_file: $CERT_FILE
  key_file: $KEY_FILE
  ca_file: $CA_FILE
  verify_and_map: true
  timeout: 2
  handshake_first: 500ms
}

tls : $TLS

leafnodes {
    port: 20023
    tls: $TLS
}
```

The leafnode has this one
```
TLS = {
  cert_file: $CERT_FILE
  key_file: $KEY_FILE
  ca_file: $CA_FILE
  verify_and_map: true
  handshake_first: 500ms
}

tls : $TLS

leafnodes {
  remotes: [
    {
      url: $SERVER
      tls {
         cert_file: $CERT_FILE
         key_file: $KEY_FILE
         ca_file: $CA_FILE
         handshake_first: true
      }
      account: $MY_ACCOUNT
    }
  ] 
}
```

In this case works, but if I remove the `handshake_first` from `remotes` section it doesn't

```
TLS = {
  cert_file: $CERT_FILE
  key_file: $KEY_FILE
  ca_file: $CA_FILE
  verify_and_map: true
  handshake_first: 500ms
}

tls : $TLS

leafnodes {
  remotes: [
    {
      url: $SERVER
      tls {
         cert_file: $CERT_FILE
         key_file: $KEY_FILE
         ca_file: $CA_FILE
      }
      account: $FILEWAVE_ACCOUNT
    }
  ] 
}
```

**Comment by kozlovic** [comment]
@mcosta74 @derekcollison Not to be pedantic, but this is not a defect. The feature of the fallback was simply not implemented for leafnodes. The documentation for the leafnode's handhsake_first only specifies the boolean. See [here](https://docs.nats.io/running-a-nats-service/configuration/leafnodes/leafnode_conf#tls-block).

The defect would be that the server does not reject this configuration, and this is simply because we use common configuration parsing that did not check that the fallback was set (and should be rejected) when parsing leafnode block.

Now, I am not suggesting that we fix the server to reject this configuration, there may be value in implementing this feature for leafnodes, but I would need confirmation from @derekcollison that this is something we want to implement.

**Comment by mcosta74** [comment]
@kozlovic Thanks for the reply. 
For us, it would be great if you'll decide to implement for leafnodes.
