### ISSUE TITLE
Expand available characters for use in Subject Names

### ISSUE THREAD

**Issue by blutack** [nats-io/nats-server#711]
- [x] Feature Request or Change Proposal
 
## Feature Requests
Define a safe character set available for use in subject names which includes some non-alphanumeric characters. Currently the specification states alphanumeric, but the server does not appear to enforce this so any characters outside of the reserved set seem to work. Because use of non-alphanumerics such as _ currently works but is not defined as safe, any changes to this in the future may cause upgrade problems for users.

It would be great if there was a set of safe non-alphanumeric characters defined as safe for use in subjects (!, #, _, ASCII, UTF-8 etc)

#### Use Case:
For some use cases, it can be beneficial to embed information into the subject name (for example events.event-01). Clients can then subscribe either on events.* or a specific event (events.event-01).
For these use cases, it is helpful to have a least a small set of safe delimiters (in a similar way to how redis keys are often composed).
 
#### Proposed Change:
Clarify/define what non-reserved (whitespace, *, ., >) characters are safe for use in subject names.
 
#### Who Benefits From The Change(s)?
NATS users with dynamically generated subject names, or that have a use case for encoding some basic information into subject names, or for escaping in subject names (for example replacing whitespace with _).
Additionally if UTF-8 were available users of non-latin languages may also benefit.

#### Alternative Approaches
- Update the server to reject all subject names which do not comply with the protocol description (may cause breakage in the wild)
- Do nothing

**Comment by blutack** [comment]
Looking at the server, it appears to treat the subject as plain bytes until a whitespace is found.
This means technically UTF-8 already works:
```

**Comment by ColinSullivan1** [comment]
I agree, we should be more specific and define behavior.  If allowing some characters beyond alnum will expand the use cases NATS can address, we should decide what can be allowed and document that.

Is there a set of characters in mind?

**Comment by sasbury** [comment]
Note - forcing UTF8 on the client libraries may be a change (it will be for Java). It is also a fairly substantial performance hit, at least for Java. Not voting against, but keep in mind that there will be a cost in work/speed. That said, we should definitely document what is supported.

**Comment by blutack** [comment]
Good point @sasbury - from my point of view ASCII would work and may be more in keeping with the simplicity of NATS. Possibly with a leading _ reserved?

**Comment by jirenius** [comment]
Was a decision made on this subject?  
If the definition is expanded to include visible ASCII characters (`c >= '!' && c <= '~'`), I could recommend using [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding) to represent any reserved characters (*space*, `*`, `>`, *leading underscore*) and to use the UTF-8 byte sequence for any non-ASCII character.

**Example**:
`user.samuel%20jir%C3%A9nius`

Since NATS already supports this, such a solution would only require clarification of the definition. And by stating an official encoding, you would avoid having all kinds of escaping methods across the NATS user base.

To make it easier to use, one could add `SubjectEscape` and `SubjectUnescape` functions/methods to client libraries, similar to [`PathEscape`](https://golang.org/pkg/net/url/#PathEscape) in Go's *url* package.

**Comment by derekcollison** [comment]
The server does support utf8, but because its a Go binary. The original design was that the control sequences and subject spaces be ascii.
