### ISSUE TITLE
v1.2.0 lost message and high delay

### ISSUE THREAD

**Issue by lightwinglc** [nats-io/nats-server#724]
recently, we upgrade gnatsd to v1.2.0, and when several days pasted(one week and sometimes 1 or 2 days), we find a few message lost, some message become high delay(we checked time, message cost seconds in nats), and we restart gnatsd service, all become OK.

**Comment by kozlovic** [comment]
Could you clarify what you mean by message lost? As you know there is no persistence in NATS, so if a subscriber is not running or gets disconnected, messages published in that time will be lost, and that's expected. Are you running a single server or a cluster? Same thing, if a sub is attached to a different node than the publisher and route between two server breaks and reconnects, messages published while the route is down are lost.

If you run with monitoring port enabled, say `-m 8222`, then you could try to get some insight as if there were slow consumers detected. The url `http://localhost:8222/connz?state=closed&subs=1` would list the closed connections with their subscriptions list and you could check the "reason" field to see if it was closed due to slow consumer situation.

**Comment by lightwinglc** [comment]
We run a cluster with about 250 gnatsd, about 2 to 4 gnatsd in 1 machine, and when problem occurred, we checked gnatsd log, no slow consumer detected, new monitor item "closed connection reason" we did not checked, we will check when problem occurred next time.
  We know there is no persistence in NATS, so program will retry if it can not get response, when problem occurred, program try many times but only a few can get response, and the situation continue until we restart nats server, and this not happend when we use v1.0.4 but already happened twice when v1.2.0. 
  And we found some message will take few seconds even few minutes in nats, which condition will cause this.

**Comment by lightwinglc** [comment]
Before in v1.0.4，when timeout detected，we will see "slow consumer detected" and see pending message in our program, but in v1.2.0, nothing can see but timeout happend.

**Comment by kozlovic** [comment]
You have a cluster of 250 servers? Being a full mesh this is a LOT of servers. But, as you said, you did not experience the problem with 1.0.4.

So we are clear, when you talk about few seconds or minutes delay, I assume this is because your requesting application does not get the response, tries again, etc.. because it is not possible for NATS to have such latency since no message is persisted. At worst, it is the latency between getting the message from the publisher and the time it takes to write to the client socket. By default, there is a deadline of 2 seconds after which the server closes the connection. Even with routes, and since this is a full mesh, the most the message will travel is 2 servers, so the max latency would be really few seconds.

Please try to see if you can get some info from the connection closed (or all) states regarding slow consumers and the like.

**Comment by derekcollison** [comment]
If a write can not complete in 2 seconds that is indicative of a systemic problem in my opinion.

**Comment by derekcollison** [comment]
Could you see if this is reproduce-able with master? v2.0.0-RC12

**Comment by lightwinglc** [comment]
We haven't tried v2.0.0-RC12 yet. And the problem may be solved after we upgrade to v1.30.

**Comment by derekcollison** [comment]
Closing this for now as being stale. Feel free to reopen.
