### ISSUE TITLE
Behaviour on overlapped subscription

### ISSUE THREAD

**Issue by nuharaf** [nats-io/nats-server#802]
- [ ] Defect
 - [ ] Feature Request or Change Proposal
 
I create this issue because I didn't see it stated anywhere in the document. If a client subscribe to an overlapped topic , say subscribing to "*" and ">" or subscribe twice to the same topic , message will be delivered by broker multiple times. I test this with nodejs client and also observe the actual data sent with wireshark.

It is not necessarily a bug per se, but a documentation clarifying this behaviour will help.
A few concern : 
 - Subscription is not exactly idempotent, because subcripting more than one cause the amount of message received changed.
 - NATS is stated as at-most-once delivery, but if the consumer accidentally subscribe twice, a message will be delivered twice.

for comparison, mosquitto broker do not deliver message multiple time on overlapped subscription [https://mosquitto.org/man/mosquitto-conf-5.html](https://mosquitto.org/man/mosquitto-conf-5.html)

**Comment by wubumihuo** [comment]
@derekcollison thanks,we have the same question. Does any nats-server version support only send the message once for multiple SIDs?

**Comment by derekcollison** [comment]
In terms of last mile to a client, a message is sent to all SIDs registered for the client. It simplifies the client logic quite a bit, otherwise clients would need to implement a full blown sublist like we have in the server.

We may have an opportunity to upgrade the client protocol later this year and could add the ability to send a message once with an array of SIDs vs just one however.
