### ISSUE TITLE
Cluster scale down

### ISSUE THREAD

**Issue by israellot** [nats-io/nats-server#824]
Is there a way to make NATS stop trying to connect to nodes that left the cluster? 
On my tests if I shutdown a node, the others keep trying to reconnect to it indefinitely. 
I can keep track of active nodes on a cluster, but I don't want to shutdown and restart remaining instances in case of a scale down just to reconfigure their routes. AFAIK there's no way to reconfigure routes dynamically after the gnastd process started.

**Comment by israellot** [comment]
Update 
I know I could signal a reload on linux or windows service. But i'm running nats in a normal process inside Service Fabric, so I would need another way to signal the process to trigger a reload.

**Comment by wallyqs** [comment]
Right, currently static routes can only be pruned by doing a reload of the configuration otherwise cluster will continue try to reconnect. In Kubernetes this can be solved by having an extra process in the same PID namespace detect the change and then signal the server, or can also be done by entering the container and sending the signal with the updated config to remove the routes.

**Comment by israellot** [comment]
I'm actually running NATS on non container Service Fabric, which means running a process on a Windows VM. What I'm looking for is another route to trigger those signals on NATS. I imagined something like Redis Server commands, or even reading from standard input.

**Comment by israellot** [comment]
I've ended up choosing to write a small wrapper around NATS in go to support signaling from different sources. I'm currently experimenting with stdin.

**Comment by derekcollison** [comment]
Going to close for now, feel free to re-open if needed.
