### ISSUE TITLE
JMS plugin

### ISSUE THREAD

**Issue by zackws** [nats-io/nats-server#933]
Hello all,
Just wanted to know how NATS handles JMS client, if its JMS compliant or not.

Thank u

**Comment by kozlovic** [comment]
@zackws JMS is a specification and client/server interaction is not specified. That is, clients use proprietary protocol to talk to their servers.

NATS does not have support for JMS clients - for reason above - but also because NATS does not offer persistence, so it would be difficult to provide features that you have in JMS.

We have NATS Streaming that gets closer to JMS in that it provides persistence.

Other approach is to use "bridges" between a JMS provider and NATS.

**Comment by zackws** [comment]
@kozlovic  thank you, another question please; can we do an apache camel bridge for nats  and activeMQ ? 
otherwise could you give an example of a bridge i can use.

**Comment by kozlovic** [comment]
@zackws We do have some connectors built by our rich community. And we also provide a framework to build your own. Check https://nats.io/download/ and https://github.com/nats-io/nats-connector-framework to see if that helps.
