### ISSUE TITLE
Document in README cluster TLS validation in dynamic environments

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-server#945]
See https://github.com/nats-io/gnatsd/issues/944. I spent a couple of hours debugging this issue and believe that it probably should be documented in README (if I've understood things correctly).

**Comment by wallyqs** [comment]
Thanks for the feedback, agree we could use some docs for this case since can be a fairly advanced setup for environments like K8S (IMO this is also a lack of good docs from K8S on how to use hostname + subdomain features from a pod to create an A record per pod that could be used against a wildcard certificate, since there is only a brief mention here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records).

**Comment by bruth** [comment]
The `cluster { advertise }` option is documented [here](https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config) and specifically notes this:

> When using TLS this is important to set to control the hostname that clients will use when discovering the route since by default this will be an IP, otherwise TLS hostname verification may fail with an IP SANs error.
